// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Data/Battle/BattleActionType.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "POGOProtos/Data/Battle/BattleActionType.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace POGOProtos {
namespace Data {
namespace Battle {

namespace {

const ::google::protobuf::EnumDescriptor* BattleActionType_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_POGOProtos_2fData_2fBattle_2fBattleActionType_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_POGOProtos_2fData_2fBattle_2fBattleActionType_2eproto() {
  protobuf_AddDesc_POGOProtos_2fData_2fBattle_2fBattleActionType_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "POGOProtos/Data/Battle/BattleActionType.proto");
  GOOGLE_CHECK(file != NULL);
  BattleActionType_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_POGOProtos_2fData_2fBattle_2fBattleActionType_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_POGOProtos_2fData_2fBattle_2fBattleActionType_2eproto() {
}

void protobuf_AddDesc_POGOProtos_2fData_2fBattle_2fBattleActionType_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_POGOProtos_2fData_2fBattle_2fBattleActionType_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n-POGOProtos/Data/Battle/BattleActionTyp"
    "e.proto\022\026POGOProtos.Data.Battle*\374\001\n\020Batt"
    "leActionType\022\020\n\014ACTION_UNSET\020\000\022\021\n\rACTION"
    "_ATTACK\020\001\022\020\n\014ACTION_DODGE\020\002\022\031\n\025ACTION_SP"
    "ECIAL_ATTACK\020\003\022\027\n\023ACTION_SWAP_POKEMON\020\004\022"
    "\020\n\014ACTION_FAINT\020\005\022\026\n\022ACTION_PLAYER_JOIN\020"
    "\006\022\026\n\022ACTION_PLAYER_QUIT\020\007\022\022\n\016ACTION_VICT"
    "ORY\020\010\022\021\n\rACTION_DEFEAT\020\t\022\024\n\020ACTION_TIMED"
    "_OUT\020\nb\006proto3", 334);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "POGOProtos/Data/Battle/BattleActionType.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_POGOProtos_2fData_2fBattle_2fBattleActionType_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_POGOProtos_2fData_2fBattle_2fBattleActionType_2eproto {
  StaticDescriptorInitializer_POGOProtos_2fData_2fBattle_2fBattleActionType_2eproto() {
    protobuf_AddDesc_POGOProtos_2fData_2fBattle_2fBattleActionType_2eproto();
  }
} static_descriptor_initializer_POGOProtos_2fData_2fBattle_2fBattleActionType_2eproto_;
const ::google::protobuf::EnumDescriptor* BattleActionType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return BattleActionType_descriptor_;
}
bool BattleActionType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Battle
}  // namespace Data
}  // namespace POGOProtos

// @@protoc_insertion_point(global_scope)
