// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Settings/Master/Item/EggIncubatorAttributes.proto

#ifndef PROTOBUF_POGOProtos_2fSettings_2fMaster_2fItem_2fEggIncubatorAttributes_2eproto__INCLUDED
#define PROTOBUF_POGOProtos_2fSettings_2fMaster_2fItem_2fEggIncubatorAttributes_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "POGOProtos/Inventory/EggIncubatorType.pb.h"
// @@protoc_insertion_point(includes)

namespace POGOProtos {
namespace Settings {
namespace Master {
namespace Item {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_POGOProtos_2fSettings_2fMaster_2fItem_2fEggIncubatorAttributes_2eproto();
void protobuf_AssignDesc_POGOProtos_2fSettings_2fMaster_2fItem_2fEggIncubatorAttributes_2eproto();
void protobuf_ShutdownFile_POGOProtos_2fSettings_2fMaster_2fItem_2fEggIncubatorAttributes_2eproto();

class EggIncubatorAttributes;

// ===================================================================

class EggIncubatorAttributes : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:POGOProtos.Settings.Master.Item.EggIncubatorAttributes) */ {
 public:
  EggIncubatorAttributes();
  virtual ~EggIncubatorAttributes();

  EggIncubatorAttributes(const EggIncubatorAttributes& from);

  inline EggIncubatorAttributes& operator=(const EggIncubatorAttributes& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const EggIncubatorAttributes& default_instance();

  void Swap(EggIncubatorAttributes* other);

  // implements Message ----------------------------------------------

  inline EggIncubatorAttributes* New() const { return New(NULL); }

  EggIncubatorAttributes* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const EggIncubatorAttributes& from);
  void MergeFrom(const EggIncubatorAttributes& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(EggIncubatorAttributes* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .POGOProtos.Inventory.EggIncubatorType incubator_type = 1;
  void clear_incubator_type();
  static const int kIncubatorTypeFieldNumber = 1;
  ::POGOProtos::Inventory::EggIncubatorType incubator_type() const;
  void set_incubator_type(::POGOProtos::Inventory::EggIncubatorType value);

  // optional int32 uses = 2;
  void clear_uses();
  static const int kUsesFieldNumber = 2;
  ::google::protobuf::int32 uses() const;
  void set_uses(::google::protobuf::int32 value);

  // optional float distance_multiplier = 3;
  void clear_distance_multiplier();
  static const int kDistanceMultiplierFieldNumber = 3;
  float distance_multiplier() const;
  void set_distance_multiplier(float value);

  // @@protoc_insertion_point(class_scope:POGOProtos.Settings.Master.Item.EggIncubatorAttributes)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  int incubator_type_;
  ::google::protobuf::int32 uses_;
  float distance_multiplier_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_POGOProtos_2fSettings_2fMaster_2fItem_2fEggIncubatorAttributes_2eproto();
  friend void protobuf_AssignDesc_POGOProtos_2fSettings_2fMaster_2fItem_2fEggIncubatorAttributes_2eproto();
  friend void protobuf_ShutdownFile_POGOProtos_2fSettings_2fMaster_2fItem_2fEggIncubatorAttributes_2eproto();

  void InitAsDefaultInstance();
  static EggIncubatorAttributes* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// EggIncubatorAttributes

// optional .POGOProtos.Inventory.EggIncubatorType incubator_type = 1;
inline void EggIncubatorAttributes::clear_incubator_type() {
  incubator_type_ = 0;
}
inline ::POGOProtos::Inventory::EggIncubatorType EggIncubatorAttributes::incubator_type() const {
  // @@protoc_insertion_point(field_get:POGOProtos.Settings.Master.Item.EggIncubatorAttributes.incubator_type)
  return static_cast< ::POGOProtos::Inventory::EggIncubatorType >(incubator_type_);
}
inline void EggIncubatorAttributes::set_incubator_type(::POGOProtos::Inventory::EggIncubatorType value) {
  
  incubator_type_ = value;
  // @@protoc_insertion_point(field_set:POGOProtos.Settings.Master.Item.EggIncubatorAttributes.incubator_type)
}

// optional int32 uses = 2;
inline void EggIncubatorAttributes::clear_uses() {
  uses_ = 0;
}
inline ::google::protobuf::int32 EggIncubatorAttributes::uses() const {
  // @@protoc_insertion_point(field_get:POGOProtos.Settings.Master.Item.EggIncubatorAttributes.uses)
  return uses_;
}
inline void EggIncubatorAttributes::set_uses(::google::protobuf::int32 value) {
  
  uses_ = value;
  // @@protoc_insertion_point(field_set:POGOProtos.Settings.Master.Item.EggIncubatorAttributes.uses)
}

// optional float distance_multiplier = 3;
inline void EggIncubatorAttributes::clear_distance_multiplier() {
  distance_multiplier_ = 0;
}
inline float EggIncubatorAttributes::distance_multiplier() const {
  // @@protoc_insertion_point(field_get:POGOProtos.Settings.Master.Item.EggIncubatorAttributes.distance_multiplier)
  return distance_multiplier_;
}
inline void EggIncubatorAttributes::set_distance_multiplier(float value) {
  
  distance_multiplier_ = value;
  // @@protoc_insertion_point(field_set:POGOProtos.Settings.Master.Item.EggIncubatorAttributes.distance_multiplier)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Item
}  // namespace Master
}  // namespace Settings
}  // namespace POGOProtos

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_POGOProtos_2fSettings_2fMaster_2fItem_2fEggIncubatorAttributes_2eproto__INCLUDED
