// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Settings/Master/Item/ExperienceBoostAttributes.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "POGOProtos/Settings/Master/Item/ExperienceBoostAttributes.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace POGOProtos {
namespace Settings {
namespace Master {
namespace Item {

namespace {

const ::google::protobuf::Descriptor* ExperienceBoostAttributes_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ExperienceBoostAttributes_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_POGOProtos_2fSettings_2fMaster_2fItem_2fExperienceBoostAttributes_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_POGOProtos_2fSettings_2fMaster_2fItem_2fExperienceBoostAttributes_2eproto() {
  protobuf_AddDesc_POGOProtos_2fSettings_2fMaster_2fItem_2fExperienceBoostAttributes_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "POGOProtos/Settings/Master/Item/ExperienceBoostAttributes.proto");
  GOOGLE_CHECK(file != NULL);
  ExperienceBoostAttributes_descriptor_ = file->message_type(0);
  static const int ExperienceBoostAttributes_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExperienceBoostAttributes, xp_multiplier_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExperienceBoostAttributes, boost_duration_ms_),
  };
  ExperienceBoostAttributes_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ExperienceBoostAttributes_descriptor_,
      ExperienceBoostAttributes::default_instance_,
      ExperienceBoostAttributes_offsets_,
      -1,
      -1,
      -1,
      sizeof(ExperienceBoostAttributes),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExperienceBoostAttributes, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExperienceBoostAttributes, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_POGOProtos_2fSettings_2fMaster_2fItem_2fExperienceBoostAttributes_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ExperienceBoostAttributes_descriptor_, &ExperienceBoostAttributes::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_POGOProtos_2fSettings_2fMaster_2fItem_2fExperienceBoostAttributes_2eproto() {
  delete ExperienceBoostAttributes::default_instance_;
  delete ExperienceBoostAttributes_reflection_;
}

void protobuf_AddDesc_POGOProtos_2fSettings_2fMaster_2fItem_2fExperienceBoostAttributes_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_POGOProtos_2fSettings_2fMaster_2fItem_2fExperienceBoostAttributes_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\?POGOProtos/Settings/Master/Item/Experi"
    "enceBoostAttributes.proto\022\037POGOProtos.Se"
    "ttings.Master.Item\"M\n\031ExperienceBoostAtt"
    "ributes\022\025\n\rxp_multiplier\030\001 \001(\002\022\031\n\021boost_"
    "duration_ms\030\002 \001(\005b\006proto3", 185);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "POGOProtos/Settings/Master/Item/ExperienceBoostAttributes.proto", &protobuf_RegisterTypes);
  ExperienceBoostAttributes::default_instance_ = new ExperienceBoostAttributes();
  ExperienceBoostAttributes::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_POGOProtos_2fSettings_2fMaster_2fItem_2fExperienceBoostAttributes_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_POGOProtos_2fSettings_2fMaster_2fItem_2fExperienceBoostAttributes_2eproto {
  StaticDescriptorInitializer_POGOProtos_2fSettings_2fMaster_2fItem_2fExperienceBoostAttributes_2eproto() {
    protobuf_AddDesc_POGOProtos_2fSettings_2fMaster_2fItem_2fExperienceBoostAttributes_2eproto();
  }
} static_descriptor_initializer_POGOProtos_2fSettings_2fMaster_2fItem_2fExperienceBoostAttributes_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ExperienceBoostAttributes::kXpMultiplierFieldNumber;
const int ExperienceBoostAttributes::kBoostDurationMsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ExperienceBoostAttributes::ExperienceBoostAttributes()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:POGOProtos.Settings.Master.Item.ExperienceBoostAttributes)
}

void ExperienceBoostAttributes::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

ExperienceBoostAttributes::ExperienceBoostAttributes(const ExperienceBoostAttributes& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:POGOProtos.Settings.Master.Item.ExperienceBoostAttributes)
}

void ExperienceBoostAttributes::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  xp_multiplier_ = 0;
  boost_duration_ms_ = 0;
}

ExperienceBoostAttributes::~ExperienceBoostAttributes() {
  // @@protoc_insertion_point(destructor:POGOProtos.Settings.Master.Item.ExperienceBoostAttributes)
  SharedDtor();
}

void ExperienceBoostAttributes::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ExperienceBoostAttributes::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ExperienceBoostAttributes::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ExperienceBoostAttributes_descriptor_;
}

const ExperienceBoostAttributes& ExperienceBoostAttributes::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_POGOProtos_2fSettings_2fMaster_2fItem_2fExperienceBoostAttributes_2eproto();
  return *default_instance_;
}

ExperienceBoostAttributes* ExperienceBoostAttributes::default_instance_ = NULL;

ExperienceBoostAttributes* ExperienceBoostAttributes::New(::google::protobuf::Arena* arena) const {
  ExperienceBoostAttributes* n = new ExperienceBoostAttributes;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ExperienceBoostAttributes::Clear() {
// @@protoc_insertion_point(message_clear_start:POGOProtos.Settings.Master.Item.ExperienceBoostAttributes)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(ExperienceBoostAttributes, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<ExperienceBoostAttributes*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(xp_multiplier_, boost_duration_ms_);

#undef ZR_HELPER_
#undef ZR_

}

bool ExperienceBoostAttributes::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:POGOProtos.Settings.Master.Item.ExperienceBoostAttributes)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional float xp_multiplier = 1;
      case 1: {
        if (tag == 13) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &xp_multiplier_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_boost_duration_ms;
        break;
      }

      // optional int32 boost_duration_ms = 2;
      case 2: {
        if (tag == 16) {
         parse_boost_duration_ms:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &boost_duration_ms_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:POGOProtos.Settings.Master.Item.ExperienceBoostAttributes)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:POGOProtos.Settings.Master.Item.ExperienceBoostAttributes)
  return false;
#undef DO_
}

void ExperienceBoostAttributes::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:POGOProtos.Settings.Master.Item.ExperienceBoostAttributes)
  // optional float xp_multiplier = 1;
  if (this->xp_multiplier() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->xp_multiplier(), output);
  }

  // optional int32 boost_duration_ms = 2;
  if (this->boost_duration_ms() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->boost_duration_ms(), output);
  }

  // @@protoc_insertion_point(serialize_end:POGOProtos.Settings.Master.Item.ExperienceBoostAttributes)
}

::google::protobuf::uint8* ExperienceBoostAttributes::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:POGOProtos.Settings.Master.Item.ExperienceBoostAttributes)
  // optional float xp_multiplier = 1;
  if (this->xp_multiplier() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->xp_multiplier(), target);
  }

  // optional int32 boost_duration_ms = 2;
  if (this->boost_duration_ms() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->boost_duration_ms(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:POGOProtos.Settings.Master.Item.ExperienceBoostAttributes)
  return target;
}

int ExperienceBoostAttributes::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:POGOProtos.Settings.Master.Item.ExperienceBoostAttributes)
  int total_size = 0;

  // optional float xp_multiplier = 1;
  if (this->xp_multiplier() != 0) {
    total_size += 1 + 4;
  }

  // optional int32 boost_duration_ms = 2;
  if (this->boost_duration_ms() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->boost_duration_ms());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ExperienceBoostAttributes::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:POGOProtos.Settings.Master.Item.ExperienceBoostAttributes)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const ExperienceBoostAttributes* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ExperienceBoostAttributes>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:POGOProtos.Settings.Master.Item.ExperienceBoostAttributes)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:POGOProtos.Settings.Master.Item.ExperienceBoostAttributes)
    MergeFrom(*source);
  }
}

void ExperienceBoostAttributes::MergeFrom(const ExperienceBoostAttributes& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:POGOProtos.Settings.Master.Item.ExperienceBoostAttributes)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.xp_multiplier() != 0) {
    set_xp_multiplier(from.xp_multiplier());
  }
  if (from.boost_duration_ms() != 0) {
    set_boost_duration_ms(from.boost_duration_ms());
  }
}

void ExperienceBoostAttributes::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:POGOProtos.Settings.Master.Item.ExperienceBoostAttributes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ExperienceBoostAttributes::CopyFrom(const ExperienceBoostAttributes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:POGOProtos.Settings.Master.Item.ExperienceBoostAttributes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ExperienceBoostAttributes::IsInitialized() const {

  return true;
}

void ExperienceBoostAttributes::Swap(ExperienceBoostAttributes* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ExperienceBoostAttributes::InternalSwap(ExperienceBoostAttributes* other) {
  std::swap(xp_multiplier_, other->xp_multiplier_);
  std::swap(boost_duration_ms_, other->boost_duration_ms_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ExperienceBoostAttributes::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ExperienceBoostAttributes_descriptor_;
  metadata.reflection = ExperienceBoostAttributes_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ExperienceBoostAttributes

// optional float xp_multiplier = 1;
void ExperienceBoostAttributes::clear_xp_multiplier() {
  xp_multiplier_ = 0;
}
 float ExperienceBoostAttributes::xp_multiplier() const {
  // @@protoc_insertion_point(field_get:POGOProtos.Settings.Master.Item.ExperienceBoostAttributes.xp_multiplier)
  return xp_multiplier_;
}
 void ExperienceBoostAttributes::set_xp_multiplier(float value) {
  
  xp_multiplier_ = value;
  // @@protoc_insertion_point(field_set:POGOProtos.Settings.Master.Item.ExperienceBoostAttributes.xp_multiplier)
}

// optional int32 boost_duration_ms = 2;
void ExperienceBoostAttributes::clear_boost_duration_ms() {
  boost_duration_ms_ = 0;
}
 ::google::protobuf::int32 ExperienceBoostAttributes::boost_duration_ms() const {
  // @@protoc_insertion_point(field_get:POGOProtos.Settings.Master.Item.ExperienceBoostAttributes.boost_duration_ms)
  return boost_duration_ms_;
}
 void ExperienceBoostAttributes::set_boost_duration_ms(::google::protobuf::int32 value) {
  
  boost_duration_ms_ = value;
  // @@protoc_insertion_point(field_set:POGOProtos.Settings.Master.Item.ExperienceBoostAttributes.boost_duration_ms)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Item
}  // namespace Master
}  // namespace Settings
}  // namespace POGOProtos

// @@protoc_insertion_point(global_scope)
