#ifndef _POGO_PROTO_H__
#define _POGO_PROTO_H__

#include "POGOProtos/Data/AssetDigestEntry.pb.h"
#include "POGOProtos/Data/Battle/BattleAction.pb.h"
#include "POGOProtos/Data/Battle/BattleActionType.pb.h"
#include "POGOProtos/Data/Battle/BattleLog.pb.h"
#include "POGOProtos/Data/Battle/BattleParticipant.pb.h"
#include "POGOProtos/Data/Battle/BattlePokemonInfo.pb.h"
#include "POGOProtos/Data/Battle/BattleResults.pb.h"
#include "POGOProtos/Data/Battle/BattleState.pb.h"
#include "POGOProtos/Data/Battle/BattleType.pb.h"
#include "POGOProtos/Data/Capture/CaptureAward.pb.h"
#include "POGOProtos/Data/Capture/CaptureProbability.pb.h"
#include "POGOProtos/Data/DownloadUrlEntry.pb.h"
#include "POGOProtos/Data/Gym/GymMembership.pb.h"
#include "POGOProtos/Data/Gym/GymState.pb.h"
#include "POGOProtos/Data/Logs/ActionLogEntry.pb.h"
#include "POGOProtos/Data/Logs/CatchPokemonLogEntry.pb.h"
#include "POGOProtos/Data/Logs/FortSearchLogEntry.pb.h"
#include "POGOProtos/Data/Player/ContactSettings.pb.h"
#include "POGOProtos/Data/Player/Currency.pb.h"
#include "POGOProtos/Data/Player/DailyBonus.pb.h"
#include "POGOProtos/Data/Player/EquippedBadge.pb.h"
#include "POGOProtos/Data/Player/PlayerAvatar.pb.h"
#include "POGOProtos/Data/Player/PlayerCamera.pb.h"
#include "POGOProtos/Data/Player/PlayerCurrency.pb.h"
#include "POGOProtos/Data/Player/PlayerPublicProfile.pb.h"
#include "POGOProtos/Data/Player/PlayerStats.pb.h"
#include "POGOProtos/Data/PlayerBadge.pb.h"
#include "POGOProtos/Data/PlayerData.pb.h"
#include "POGOProtos/Data/PokedexEntry.pb.h"
#include "POGOProtos/Data/PokemonData.pb.h"
#include "POGOProtos/Enums/ActivityType.pb.h"
#include "POGOProtos/Enums/BadgeType.pb.h"
#include "POGOProtos/Enums/CameraInterpolation.pb.h"
#include "POGOProtos/Enums/CameraTarget.pb.h"
#include "POGOProtos/Enums/Gender.pb.h"
#include "POGOProtos/Enums/IapItemCategory.pb.h"
#include "POGOProtos/Enums/ItemCategory.pb.h"
#include "POGOProtos/Enums/ItemEffect.pb.h"
#include "POGOProtos/Enums/Platform.pb.h"
#include "POGOProtos/Enums/PokemonFamilyId.pb.h"
#include "POGOProtos/Enums/PokemonId.pb.h"
#include "POGOProtos/Enums/PokemonMove.pb.h"
#include "POGOProtos/Enums/PokemonMovementType.pb.h"
#include "POGOProtos/Enums/PokemonRarity.pb.h"
#include "POGOProtos/Enums/PokemonType.pb.h"
#include "POGOProtos/Enums/TeamColor.pb.h"
#include "POGOProtos/Enums/TutorialState.pb.h"
#include "POGOProtos/Inventory/AppliedItem.pb.h"
#include "POGOProtos/Inventory/AppliedItems.pb.h"
#include "POGOProtos/Inventory/Candy.pb.h"
#include "POGOProtos/Inventory/EggIncubator.pb.h"
#include "POGOProtos/Inventory/EggIncubators.pb.h"
#include "POGOProtos/Inventory/EggIncubatorType.pb.h"
#include "POGOProtos/Inventory/InventoryDelta.pb.h"
#include "POGOProtos/Inventory/InventoryItem.pb.h"
#include "POGOProtos/Inventory/InventoryItemData.pb.h"
#include "POGOProtos/Inventory/InventoryUpgrade.pb.h"
#include "POGOProtos/Inventory/InventoryUpgrades.pb.h"
#include "POGOProtos/Inventory/InventoryUpgradeType.pb.h"
#include "POGOProtos/Inventory/Item/ItemAward.pb.h"
#include "POGOProtos/Inventory/Item/ItemData.pb.h"
#include "POGOProtos/Inventory/Item/ItemId.pb.h"
#include "POGOProtos/Inventory/Item/ItemType.pb.h"
#include "POGOProtos/Map/Fort/FortData.pb.h"
#include "POGOProtos/Map/Fort/FortLureInfo.pb.h"
#include "POGOProtos/Map/Fort/FortModifier.pb.h"
#include "POGOProtos/Map/Fort/FortRenderingType.pb.h"
#include "POGOProtos/Map/Fort/FortSponsor.pb.h"
#include "POGOProtos/Map/Fort/FortSummary.pb.h"
#include "POGOProtos/Map/Fort/FortType.pb.h"
#include "POGOProtos/Map/MapCell.pb.h"
#include "POGOProtos/Map/MapObjectsStatus.pb.h"
#include "POGOProtos/Map/Pokemon/MapPokemon.pb.h"
#include "POGOProtos/Map/Pokemon/NearbyPokemon.pb.h"
#include "POGOProtos/Map/Pokemon/WildPokemon.pb.h"
#include "POGOProtos/Map/SpawnPoint.pb.h"
#include "POGOProtos/Networking/Envelopes/AuthTicket.pb.h"
#include "POGOProtos/Networking/Envelopes/RequestEnvelope.pb.h"
#include "POGOProtos/Networking/Envelopes/ResponseEnvelope.pb.h"
#include "POGOProtos/Networking/Envelopes/Signature.pb.h"
#include "POGOProtos/Networking/Envelopes/Unknown6.pb.h"
#include "POGOProtos/Networking/Envelopes/Unknown6Response.pb.h"
#include "POGOProtos/Networking/Requests/Messages/AddFortModifierMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/AttackGymMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/CatchPokemonMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/CheckAwardedBadgesMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/CheckCodenameAvailableMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/ClaimCodenameMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/CollectDailyBonusMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/CollectDailyDefenderBonusMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/DiskEncounterMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/DownloadItemTemplatesMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/DownloadRemoteConfigVersionMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/DownloadSettingsMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/EchoMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/EncounterMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/EncounterTutorialCompleteMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/EquipBadgeMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/EvolvePokemonMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/FortDeployPokemonMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/FortDetailsMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/FortRecallPokemonMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/FortSearchMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/GetAssetDigestMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/GetDownloadUrlsMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/GetGymDetailsMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/GetHatchedEggsMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/GetIncensePokemonMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/GetInventoryMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/GetMapObjectsMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/GetPlayerMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/GetPlayerProfileMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/GetSuggestedCodenamesMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/IncenseEncounterMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/LevelUpRewardsMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/MarkTutorialCompleteMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/NicknamePokemonMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/PlayerUpdateMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/RecycleInventoryItemMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/ReleasePokemonMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/SetAvatarMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/SetContactSettingsMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/SetFavoritePokemonMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/SetPlayerTeamMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/SfidaActionLogMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/StartGymBattleMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/UpgradePokemonMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/UseIncenseMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/UseItemCaptureMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/UseItemEggIncubatorMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/UseItemGymMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/UseItemPotionMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/UseItemReviveMessage.pb.h"
#include "POGOProtos/Networking/Requests/Messages/UseItemXpBoostMessage.pb.h"
#include "POGOProtos/Networking/Requests/Request.pb.h"
#include "POGOProtos/Networking/Requests/RequestType.pb.h"
#include "POGOProtos/Networking/Responses/AddFortModifierResponse.pb.h"
#include "POGOProtos/Networking/Responses/AttackGymResponse.pb.h"
#include "POGOProtos/Networking/Responses/CatchPokemonResponse.pb.h"
#include "POGOProtos/Networking/Responses/CheckAwardedBadgesResponse.pb.h"
#include "POGOProtos/Networking/Responses/CheckCodenameAvailableResponse.pb.h"
#include "POGOProtos/Networking/Responses/ClaimCodenameResponse.pb.h"
#include "POGOProtos/Networking/Responses/CollectDailyBonusResponse.pb.h"
#include "POGOProtos/Networking/Responses/CollectDailyDefenderBonusResponse.pb.h"
#include "POGOProtos/Networking/Responses/DiskEncounterResponse.pb.h"
#include "POGOProtos/Networking/Responses/DownloadItemTemplatesResponse.pb.h"
#include "POGOProtos/Networking/Responses/DownloadRemoteConfigVersionResponse.pb.h"
#include "POGOProtos/Networking/Responses/DownloadSettingsResponse.pb.h"
#include "POGOProtos/Networking/Responses/EchoResponse.pb.h"
#include "POGOProtos/Networking/Responses/EncounterResponse.pb.h"
#include "POGOProtos/Networking/Responses/EncounterTutorialCompleteResponse.pb.h"
#include "POGOProtos/Networking/Responses/EquipBadgeResponse.pb.h"
#include "POGOProtos/Networking/Responses/EvolvePokemonResponse.pb.h"
#include "POGOProtos/Networking/Responses/FortDeployPokemonResponse.pb.h"
#include "POGOProtos/Networking/Responses/FortDetailsResponse.pb.h"
#include "POGOProtos/Networking/Responses/FortRecallPokemonResponse.pb.h"
#include "POGOProtos/Networking/Responses/FortSearchResponse.pb.h"
#include "POGOProtos/Networking/Responses/GetAssetDigestResponse.pb.h"
#include "POGOProtos/Networking/Responses/GetDownloadUrlsResponse.pb.h"
#include "POGOProtos/Networking/Responses/GetGymDetailsResponse.pb.h"
#include "POGOProtos/Networking/Responses/GetHatchedEggsResponse.pb.h"
#include "POGOProtos/Networking/Responses/GetIncensePokemonResponse.pb.h"
#include "POGOProtos/Networking/Responses/GetInventoryResponse.pb.h"
#include "POGOProtos/Networking/Responses/GetMapObjectsResponse.pb.h"
#include "POGOProtos/Networking/Responses/GetPlayerProfileResponse.pb.h"
#include "POGOProtos/Networking/Responses/GetPlayerResponse.pb.h"
#include "POGOProtos/Networking/Responses/GetSuggestedCodenamesResponse.pb.h"
#include "POGOProtos/Networking/Responses/IncenseEncounterResponse.pb.h"
#include "POGOProtos/Networking/Responses/LevelUpRewardsResponse.pb.h"
#include "POGOProtos/Networking/Responses/MarkTutorialCompleteResponse.pb.h"
#include "POGOProtos/Networking/Responses/NicknamePokemonResponse.pb.h"
#include "POGOProtos/Networking/Responses/PlayerUpdateResponse.pb.h"
#include "POGOProtos/Networking/Responses/RecycleInventoryItemResponse.pb.h"
#include "POGOProtos/Networking/Responses/ReleasePokemonResponse.pb.h"
#include "POGOProtos/Networking/Responses/SetAvatarResponse.pb.h"
#include "POGOProtos/Networking/Responses/SetContactSettingsResponse.pb.h"
#include "POGOProtos/Networking/Responses/SetFavoritePokemonResponse.pb.h"
#include "POGOProtos/Networking/Responses/SetPlayerTeamResponse.pb.h"
#include "POGOProtos/Networking/Responses/SfidaActionLogResponse.pb.h"
#include "POGOProtos/Networking/Responses/StartGymBattleResponse.pb.h"
#include "POGOProtos/Networking/Responses/UpgradePokemonResponse.pb.h"
#include "POGOProtos/Networking/Responses/UseIncenseResponse.pb.h"
#include "POGOProtos/Networking/Responses/UseItemCaptureResponse.pb.h"
#include "POGOProtos/Networking/Responses/UseItemEggIncubatorResponse.pb.h"
#include "POGOProtos/Networking/Responses/UseItemGymResponse.pb.h"
#include "POGOProtos/Networking/Responses/UseItemPotionResponse.pb.h"
#include "POGOProtos/Networking/Responses/UseItemReviveResponse.pb.h"
#include "POGOProtos/Networking/Responses/UseItemXpBoostResponse.pb.h"
#include "POGOProtos/Settings/DownloadSettingsAction.pb.h"
#include "POGOProtos/Settings/FortSettings.pb.h"
#include "POGOProtos/Settings/GlobalSettings.pb.h"
#include "POGOProtos/Settings/InventorySettings.pb.h"
#include "POGOProtos/Settings/LevelSettings.pb.h"
#include "POGOProtos/Settings/MapSettings.pb.h"
#include "POGOProtos/Settings/Master/BadgeSettings.pb.h"
#include "POGOProtos/Settings/Master/CameraSettings.pb.h"
#include "POGOProtos/Settings/Master/EncounterSettings.pb.h"
#include "POGOProtos/Settings/Master/EquippedBadgeSettings.pb.h"
#include "POGOProtos/Settings/Master/GymBattleSettings.pb.h"
#include "POGOProtos/Settings/Master/GymLevelSettings.pb.h"
#include "POGOProtos/Settings/Master/IapItemDisplay.pb.h"
#include "POGOProtos/Settings/Master/IapSettings.pb.h"
#include "POGOProtos/Settings/Master/Item/BattleAttributes.pb.h"
#include "POGOProtos/Settings/Master/Item/EggIncubatorAttributes.pb.h"
#include "POGOProtos/Settings/Master/Item/ExperienceBoostAttributes.pb.h"
#include "POGOProtos/Settings/Master/Item/FoodAttributes.pb.h"
#include "POGOProtos/Settings/Master/Item/FortModifierAttributes.pb.h"
#include "POGOProtos/Settings/Master/Item/IncenseAttributes.pb.h"
#include "POGOProtos/Settings/Master/Item/InventoryUpgradeAttributes.pb.h"
#include "POGOProtos/Settings/Master/Item/PokeballAttributes.pb.h"
#include "POGOProtos/Settings/Master/Item/PotionAttributes.pb.h"
#include "POGOProtos/Settings/Master/Item/ReviveAttributes.pb.h"
#include "POGOProtos/Settings/Master/ItemSettings.pb.h"
#include "POGOProtos/Settings/Master/MoveSequenceSettings.pb.h"
#include "POGOProtos/Settings/Master/MoveSettings.pb.h"
#include "POGOProtos/Settings/Master/PlayerLevelSettings.pb.h"
#include "POGOProtos/Settings/Master/Pokemon/CameraAttributes.pb.h"
#include "POGOProtos/Settings/Master/Pokemon/EncounterAttributes.pb.h"
#include "POGOProtos/Settings/Master/Pokemon/StatsAttributes.pb.h"
#include "POGOProtos/Settings/Master/PokemonSettings.pb.h"
#include "POGOProtos/Settings/Master/PokemonUpgradeSettings.pb.h"
#include "POGOProtos/Settings/Master/TypeEffectiveSettings.pb.h"


namespace pogo
{
  using namespace POGOProtos;
  using namespace POGOProtos::Data;
  using namespace POGOProtos::Data::Battle;
  using namespace POGOProtos::Data::Capture;
  using namespace POGOProtos::Data::Gym;
  using namespace POGOProtos::Data::Logs;
  using namespace POGOProtos::Data::Player;
  using namespace POGOProtos::Enums;
  using namespace POGOProtos::Inventory;
  using namespace POGOProtos::Inventory::Item;
  using namespace POGOProtos::Map;
  using namespace POGOProtos::Map::Fort;
  using namespace POGOProtos::Map::Pokemon;
  using namespace POGOProtos::Networking;
  using namespace POGOProtos::Networking::Envelopes;
  using namespace POGOProtos::Networking::Requests;
  using namespace POGOProtos::Networking::Requests::Messages;
  using namespace POGOProtos::Networking::Responses;
  using namespace POGOProtos::Settings;
  using namespace POGOProtos::Settings::Master;
  using namespace POGOProtos::Settings::Master::Item;
  using namespace POGOProtos::Settings::Master::Pokemon;
}

#endif //_POGO_PROTO_H__
