// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Requests/Messages/ClaimCodenameMessage.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "POGOProtos/Networking/Requests/Messages/ClaimCodenameMessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace POGOProtos {
namespace Networking {
namespace Requests {
namespace Messages {

namespace {

const ::google::protobuf::Descriptor* ClaimCodenameMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ClaimCodenameMessage_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_POGOProtos_2fNetworking_2fRequests_2fMessages_2fClaimCodenameMessage_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_POGOProtos_2fNetworking_2fRequests_2fMessages_2fClaimCodenameMessage_2eproto() {
  protobuf_AddDesc_POGOProtos_2fNetworking_2fRequests_2fMessages_2fClaimCodenameMessage_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "POGOProtos/Networking/Requests/Messages/ClaimCodenameMessage.proto");
  GOOGLE_CHECK(file != NULL);
  ClaimCodenameMessage_descriptor_ = file->message_type(0);
  static const int ClaimCodenameMessage_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClaimCodenameMessage, codename_),
  };
  ClaimCodenameMessage_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ClaimCodenameMessage_descriptor_,
      ClaimCodenameMessage::default_instance_,
      ClaimCodenameMessage_offsets_,
      -1,
      -1,
      -1,
      sizeof(ClaimCodenameMessage),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClaimCodenameMessage, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClaimCodenameMessage, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_POGOProtos_2fNetworking_2fRequests_2fMessages_2fClaimCodenameMessage_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ClaimCodenameMessage_descriptor_, &ClaimCodenameMessage::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_POGOProtos_2fNetworking_2fRequests_2fMessages_2fClaimCodenameMessage_2eproto() {
  delete ClaimCodenameMessage::default_instance_;
  delete ClaimCodenameMessage_reflection_;
}

void protobuf_AddDesc_POGOProtos_2fNetworking_2fRequests_2fMessages_2fClaimCodenameMessage_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_POGOProtos_2fNetworking_2fRequests_2fMessages_2fClaimCodenameMessage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\nBPOGOProtos/Networking/Requests/Message"
    "s/ClaimCodenameMessage.proto\022\'POGOProtos"
    ".Networking.Requests.Messages\"(\n\024ClaimCo"
    "denameMessage\022\020\n\010codename\030\001 \001(\tb\006proto3", 159);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "POGOProtos/Networking/Requests/Messages/ClaimCodenameMessage.proto", &protobuf_RegisterTypes);
  ClaimCodenameMessage::default_instance_ = new ClaimCodenameMessage();
  ClaimCodenameMessage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_POGOProtos_2fNetworking_2fRequests_2fMessages_2fClaimCodenameMessage_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_POGOProtos_2fNetworking_2fRequests_2fMessages_2fClaimCodenameMessage_2eproto {
  StaticDescriptorInitializer_POGOProtos_2fNetworking_2fRequests_2fMessages_2fClaimCodenameMessage_2eproto() {
    protobuf_AddDesc_POGOProtos_2fNetworking_2fRequests_2fMessages_2fClaimCodenameMessage_2eproto();
  }
} static_descriptor_initializer_POGOProtos_2fNetworking_2fRequests_2fMessages_2fClaimCodenameMessage_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ClaimCodenameMessage::kCodenameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ClaimCodenameMessage::ClaimCodenameMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage)
}

void ClaimCodenameMessage::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

ClaimCodenameMessage::ClaimCodenameMessage(const ClaimCodenameMessage& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage)
}

void ClaimCodenameMessage::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  codename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

ClaimCodenameMessage::~ClaimCodenameMessage() {
  // @@protoc_insertion_point(destructor:POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage)
  SharedDtor();
}

void ClaimCodenameMessage::SharedDtor() {
  codename_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void ClaimCodenameMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ClaimCodenameMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ClaimCodenameMessage_descriptor_;
}

const ClaimCodenameMessage& ClaimCodenameMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_POGOProtos_2fNetworking_2fRequests_2fMessages_2fClaimCodenameMessage_2eproto();
  return *default_instance_;
}

ClaimCodenameMessage* ClaimCodenameMessage::default_instance_ = NULL;

ClaimCodenameMessage* ClaimCodenameMessage::New(::google::protobuf::Arena* arena) const {
  ClaimCodenameMessage* n = new ClaimCodenameMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ClaimCodenameMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage)
  codename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool ClaimCodenameMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string codename = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_codename()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->codename().data(), this->codename().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage.codename"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage)
  return false;
#undef DO_
}

void ClaimCodenameMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage)
  // optional string codename = 1;
  if (this->codename().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->codename().data(), this->codename().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage.codename");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->codename(), output);
  }

  // @@protoc_insertion_point(serialize_end:POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage)
}

::google::protobuf::uint8* ClaimCodenameMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage)
  // optional string codename = 1;
  if (this->codename().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->codename().data(), this->codename().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage.codename");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->codename(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage)
  return target;
}

int ClaimCodenameMessage::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage)
  int total_size = 0;

  // optional string codename = 1;
  if (this->codename().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->codename());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ClaimCodenameMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const ClaimCodenameMessage* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ClaimCodenameMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage)
    MergeFrom(*source);
  }
}

void ClaimCodenameMessage::MergeFrom(const ClaimCodenameMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.codename().size() > 0) {

    codename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.codename_);
  }
}

void ClaimCodenameMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClaimCodenameMessage::CopyFrom(const ClaimCodenameMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClaimCodenameMessage::IsInitialized() const {

  return true;
}

void ClaimCodenameMessage::Swap(ClaimCodenameMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ClaimCodenameMessage::InternalSwap(ClaimCodenameMessage* other) {
  codename_.Swap(&other->codename_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ClaimCodenameMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ClaimCodenameMessage_descriptor_;
  metadata.reflection = ClaimCodenameMessage_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ClaimCodenameMessage

// optional string codename = 1;
void ClaimCodenameMessage::clear_codename() {
  codename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& ClaimCodenameMessage::codename() const {
  // @@protoc_insertion_point(field_get:POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage.codename)
  return codename_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ClaimCodenameMessage::set_codename(const ::std::string& value) {
  
  codename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage.codename)
}
 void ClaimCodenameMessage::set_codename(const char* value) {
  
  codename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage.codename)
}
 void ClaimCodenameMessage::set_codename(const char* value, size_t size) {
  
  codename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage.codename)
}
 ::std::string* ClaimCodenameMessage::mutable_codename() {
  
  // @@protoc_insertion_point(field_mutable:POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage.codename)
  return codename_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* ClaimCodenameMessage::release_codename() {
  // @@protoc_insertion_point(field_release:POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage.codename)
  
  return codename_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ClaimCodenameMessage::set_allocated_codename(::std::string* codename) {
  if (codename != NULL) {
    
  } else {
    
  }
  codename_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), codename);
  // @@protoc_insertion_point(field_set_allocated:POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage.codename)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Messages
}  // namespace Requests
}  // namespace Networking
}  // namespace POGOProtos

// @@protoc_insertion_point(global_scope)
