// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Responses/EncounterTutorialCompleteResponse.proto

#ifndef PROTOBUF_POGOProtos_2fNetworking_2fResponses_2fEncounterTutorialCompleteResponse_2eproto__INCLUDED
#define PROTOBUF_POGOProtos_2fNetworking_2fResponses_2fEncounterTutorialCompleteResponse_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "POGOProtos/Data/PokemonData.pb.h"
#include "POGOProtos/Data/Capture/CaptureAward.pb.h"
// @@protoc_insertion_point(includes)

namespace POGOProtos {
namespace Networking {
namespace Responses {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_POGOProtos_2fNetworking_2fResponses_2fEncounterTutorialCompleteResponse_2eproto();
void protobuf_AssignDesc_POGOProtos_2fNetworking_2fResponses_2fEncounterTutorialCompleteResponse_2eproto();
void protobuf_ShutdownFile_POGOProtos_2fNetworking_2fResponses_2fEncounterTutorialCompleteResponse_2eproto();

class EncounterTutorialCompleteResponse;

enum EncounterTutorialCompleteResponse_Result {
  EncounterTutorialCompleteResponse_Result_UNSET = 0,
  EncounterTutorialCompleteResponse_Result_SUCCESS = 1,
  EncounterTutorialCompleteResponse_Result_ERROR_INVALID_POKEMON = 2,
  EncounterTutorialCompleteResponse_Result_EncounterTutorialCompleteResponse_Result_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  EncounterTutorialCompleteResponse_Result_EncounterTutorialCompleteResponse_Result_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool EncounterTutorialCompleteResponse_Result_IsValid(int value);
const EncounterTutorialCompleteResponse_Result EncounterTutorialCompleteResponse_Result_Result_MIN = EncounterTutorialCompleteResponse_Result_UNSET;
const EncounterTutorialCompleteResponse_Result EncounterTutorialCompleteResponse_Result_Result_MAX = EncounterTutorialCompleteResponse_Result_ERROR_INVALID_POKEMON;
const int EncounterTutorialCompleteResponse_Result_Result_ARRAYSIZE = EncounterTutorialCompleteResponse_Result_Result_MAX + 1;

const ::google::protobuf::EnumDescriptor* EncounterTutorialCompleteResponse_Result_descriptor();
inline const ::std::string& EncounterTutorialCompleteResponse_Result_Name(EncounterTutorialCompleteResponse_Result value) {
  return ::google::protobuf::internal::NameOfEnum(
    EncounterTutorialCompleteResponse_Result_descriptor(), value);
}
inline bool EncounterTutorialCompleteResponse_Result_Parse(
    const ::std::string& name, EncounterTutorialCompleteResponse_Result* value) {
  return ::google::protobuf::internal::ParseNamedEnum<EncounterTutorialCompleteResponse_Result>(
    EncounterTutorialCompleteResponse_Result_descriptor(), name, value);
}
// ===================================================================

class EncounterTutorialCompleteResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:POGOProtos.Networking.Responses.EncounterTutorialCompleteResponse) */ {
 public:
  EncounterTutorialCompleteResponse();
  virtual ~EncounterTutorialCompleteResponse();

  EncounterTutorialCompleteResponse(const EncounterTutorialCompleteResponse& from);

  inline EncounterTutorialCompleteResponse& operator=(const EncounterTutorialCompleteResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const EncounterTutorialCompleteResponse& default_instance();

  void Swap(EncounterTutorialCompleteResponse* other);

  // implements Message ----------------------------------------------

  inline EncounterTutorialCompleteResponse* New() const { return New(NULL); }

  EncounterTutorialCompleteResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const EncounterTutorialCompleteResponse& from);
  void MergeFrom(const EncounterTutorialCompleteResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(EncounterTutorialCompleteResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef EncounterTutorialCompleteResponse_Result Result;
  static const Result UNSET =
    EncounterTutorialCompleteResponse_Result_UNSET;
  static const Result SUCCESS =
    EncounterTutorialCompleteResponse_Result_SUCCESS;
  static const Result ERROR_INVALID_POKEMON =
    EncounterTutorialCompleteResponse_Result_ERROR_INVALID_POKEMON;
  static inline bool Result_IsValid(int value) {
    return EncounterTutorialCompleteResponse_Result_IsValid(value);
  }
  static const Result Result_MIN =
    EncounterTutorialCompleteResponse_Result_Result_MIN;
  static const Result Result_MAX =
    EncounterTutorialCompleteResponse_Result_Result_MAX;
  static const int Result_ARRAYSIZE =
    EncounterTutorialCompleteResponse_Result_Result_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Result_descriptor() {
    return EncounterTutorialCompleteResponse_Result_descriptor();
  }
  static inline const ::std::string& Result_Name(Result value) {
    return EncounterTutorialCompleteResponse_Result_Name(value);
  }
  static inline bool Result_Parse(const ::std::string& name,
      Result* value) {
    return EncounterTutorialCompleteResponse_Result_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .POGOProtos.Networking.Responses.EncounterTutorialCompleteResponse.Result result = 1;
  void clear_result();
  static const int kResultFieldNumber = 1;
  ::POGOProtos::Networking::Responses::EncounterTutorialCompleteResponse_Result result() const;
  void set_result(::POGOProtos::Networking::Responses::EncounterTutorialCompleteResponse_Result value);

  // optional .POGOProtos.Data.PokemonData pokemon_data = 2;
  bool has_pokemon_data() const;
  void clear_pokemon_data();
  static const int kPokemonDataFieldNumber = 2;
  const ::POGOProtos::Data::PokemonData& pokemon_data() const;
  ::POGOProtos::Data::PokemonData* mutable_pokemon_data();
  ::POGOProtos::Data::PokemonData* release_pokemon_data();
  void set_allocated_pokemon_data(::POGOProtos::Data::PokemonData* pokemon_data);

  // optional .POGOProtos.Data.Capture.CaptureAward capture_award = 3;
  bool has_capture_award() const;
  void clear_capture_award();
  static const int kCaptureAwardFieldNumber = 3;
  const ::POGOProtos::Data::Capture::CaptureAward& capture_award() const;
  ::POGOProtos::Data::Capture::CaptureAward* mutable_capture_award();
  ::POGOProtos::Data::Capture::CaptureAward* release_capture_award();
  void set_allocated_capture_award(::POGOProtos::Data::Capture::CaptureAward* capture_award);

  // @@protoc_insertion_point(class_scope:POGOProtos.Networking.Responses.EncounterTutorialCompleteResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::POGOProtos::Data::PokemonData* pokemon_data_;
  ::POGOProtos::Data::Capture::CaptureAward* capture_award_;
  int result_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_POGOProtos_2fNetworking_2fResponses_2fEncounterTutorialCompleteResponse_2eproto();
  friend void protobuf_AssignDesc_POGOProtos_2fNetworking_2fResponses_2fEncounterTutorialCompleteResponse_2eproto();
  friend void protobuf_ShutdownFile_POGOProtos_2fNetworking_2fResponses_2fEncounterTutorialCompleteResponse_2eproto();

  void InitAsDefaultInstance();
  static EncounterTutorialCompleteResponse* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// EncounterTutorialCompleteResponse

// optional .POGOProtos.Networking.Responses.EncounterTutorialCompleteResponse.Result result = 1;
inline void EncounterTutorialCompleteResponse::clear_result() {
  result_ = 0;
}
inline ::POGOProtos::Networking::Responses::EncounterTutorialCompleteResponse_Result EncounterTutorialCompleteResponse::result() const {
  // @@protoc_insertion_point(field_get:POGOProtos.Networking.Responses.EncounterTutorialCompleteResponse.result)
  return static_cast< ::POGOProtos::Networking::Responses::EncounterTutorialCompleteResponse_Result >(result_);
}
inline void EncounterTutorialCompleteResponse::set_result(::POGOProtos::Networking::Responses::EncounterTutorialCompleteResponse_Result value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:POGOProtos.Networking.Responses.EncounterTutorialCompleteResponse.result)
}

// optional .POGOProtos.Data.PokemonData pokemon_data = 2;
inline bool EncounterTutorialCompleteResponse::has_pokemon_data() const {
  return !_is_default_instance_ && pokemon_data_ != NULL;
}
inline void EncounterTutorialCompleteResponse::clear_pokemon_data() {
  if (GetArenaNoVirtual() == NULL && pokemon_data_ != NULL) delete pokemon_data_;
  pokemon_data_ = NULL;
}
inline const ::POGOProtos::Data::PokemonData& EncounterTutorialCompleteResponse::pokemon_data() const {
  // @@protoc_insertion_point(field_get:POGOProtos.Networking.Responses.EncounterTutorialCompleteResponse.pokemon_data)
  return pokemon_data_ != NULL ? *pokemon_data_ : *default_instance_->pokemon_data_;
}
inline ::POGOProtos::Data::PokemonData* EncounterTutorialCompleteResponse::mutable_pokemon_data() {
  
  if (pokemon_data_ == NULL) {
    pokemon_data_ = new ::POGOProtos::Data::PokemonData;
  }
  // @@protoc_insertion_point(field_mutable:POGOProtos.Networking.Responses.EncounterTutorialCompleteResponse.pokemon_data)
  return pokemon_data_;
}
inline ::POGOProtos::Data::PokemonData* EncounterTutorialCompleteResponse::release_pokemon_data() {
  // @@protoc_insertion_point(field_release:POGOProtos.Networking.Responses.EncounterTutorialCompleteResponse.pokemon_data)
  
  ::POGOProtos::Data::PokemonData* temp = pokemon_data_;
  pokemon_data_ = NULL;
  return temp;
}
inline void EncounterTutorialCompleteResponse::set_allocated_pokemon_data(::POGOProtos::Data::PokemonData* pokemon_data) {
  delete pokemon_data_;
  pokemon_data_ = pokemon_data;
  if (pokemon_data) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:POGOProtos.Networking.Responses.EncounterTutorialCompleteResponse.pokemon_data)
}

// optional .POGOProtos.Data.Capture.CaptureAward capture_award = 3;
inline bool EncounterTutorialCompleteResponse::has_capture_award() const {
  return !_is_default_instance_ && capture_award_ != NULL;
}
inline void EncounterTutorialCompleteResponse::clear_capture_award() {
  if (GetArenaNoVirtual() == NULL && capture_award_ != NULL) delete capture_award_;
  capture_award_ = NULL;
}
inline const ::POGOProtos::Data::Capture::CaptureAward& EncounterTutorialCompleteResponse::capture_award() const {
  // @@protoc_insertion_point(field_get:POGOProtos.Networking.Responses.EncounterTutorialCompleteResponse.capture_award)
  return capture_award_ != NULL ? *capture_award_ : *default_instance_->capture_award_;
}
inline ::POGOProtos::Data::Capture::CaptureAward* EncounterTutorialCompleteResponse::mutable_capture_award() {
  
  if (capture_award_ == NULL) {
    capture_award_ = new ::POGOProtos::Data::Capture::CaptureAward;
  }
  // @@protoc_insertion_point(field_mutable:POGOProtos.Networking.Responses.EncounterTutorialCompleteResponse.capture_award)
  return capture_award_;
}
inline ::POGOProtos::Data::Capture::CaptureAward* EncounterTutorialCompleteResponse::release_capture_award() {
  // @@protoc_insertion_point(field_release:POGOProtos.Networking.Responses.EncounterTutorialCompleteResponse.capture_award)
  
  ::POGOProtos::Data::Capture::CaptureAward* temp = capture_award_;
  capture_award_ = NULL;
  return temp;
}
inline void EncounterTutorialCompleteResponse::set_allocated_capture_award(::POGOProtos::Data::Capture::CaptureAward* capture_award) {
  delete capture_award_;
  capture_award_ = capture_award;
  if (capture_award) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:POGOProtos.Networking.Responses.EncounterTutorialCompleteResponse.capture_award)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Responses
}  // namespace Networking
}  // namespace POGOProtos

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::POGOProtos::Networking::Responses::EncounterTutorialCompleteResponse_Result> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::POGOProtos::Networking::Responses::EncounterTutorialCompleteResponse_Result>() {
  return ::POGOProtos::Networking::Responses::EncounterTutorialCompleteResponse_Result_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_POGOProtos_2fNetworking_2fResponses_2fEncounterTutorialCompleteResponse_2eproto__INCLUDED
