// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Responses/SetPlayerTeamResponse.proto

#ifndef PROTOBUF_POGOProtos_2fNetworking_2fResponses_2fSetPlayerTeamResponse_2eproto__INCLUDED
#define PROTOBUF_POGOProtos_2fNetworking_2fResponses_2fSetPlayerTeamResponse_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "POGOProtos/Data/PlayerData.pb.h"
// @@protoc_insertion_point(includes)

namespace POGOProtos {
namespace Networking {
namespace Responses {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_POGOProtos_2fNetworking_2fResponses_2fSetPlayerTeamResponse_2eproto();
void protobuf_AssignDesc_POGOProtos_2fNetworking_2fResponses_2fSetPlayerTeamResponse_2eproto();
void protobuf_ShutdownFile_POGOProtos_2fNetworking_2fResponses_2fSetPlayerTeamResponse_2eproto();

class SetPlayerTeamResponse;

enum SetPlayerTeamResponse_Status {
  SetPlayerTeamResponse_Status_UNSET = 0,
  SetPlayerTeamResponse_Status_SUCCESS = 1,
  SetPlayerTeamResponse_Status_TEAM_ALREADY_SET = 2,
  SetPlayerTeamResponse_Status_FAILURE = 3,
  SetPlayerTeamResponse_Status_SetPlayerTeamResponse_Status_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  SetPlayerTeamResponse_Status_SetPlayerTeamResponse_Status_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool SetPlayerTeamResponse_Status_IsValid(int value);
const SetPlayerTeamResponse_Status SetPlayerTeamResponse_Status_Status_MIN = SetPlayerTeamResponse_Status_UNSET;
const SetPlayerTeamResponse_Status SetPlayerTeamResponse_Status_Status_MAX = SetPlayerTeamResponse_Status_FAILURE;
const int SetPlayerTeamResponse_Status_Status_ARRAYSIZE = SetPlayerTeamResponse_Status_Status_MAX + 1;

const ::google::protobuf::EnumDescriptor* SetPlayerTeamResponse_Status_descriptor();
inline const ::std::string& SetPlayerTeamResponse_Status_Name(SetPlayerTeamResponse_Status value) {
  return ::google::protobuf::internal::NameOfEnum(
    SetPlayerTeamResponse_Status_descriptor(), value);
}
inline bool SetPlayerTeamResponse_Status_Parse(
    const ::std::string& name, SetPlayerTeamResponse_Status* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SetPlayerTeamResponse_Status>(
    SetPlayerTeamResponse_Status_descriptor(), name, value);
}
// ===================================================================

class SetPlayerTeamResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:POGOProtos.Networking.Responses.SetPlayerTeamResponse) */ {
 public:
  SetPlayerTeamResponse();
  virtual ~SetPlayerTeamResponse();

  SetPlayerTeamResponse(const SetPlayerTeamResponse& from);

  inline SetPlayerTeamResponse& operator=(const SetPlayerTeamResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SetPlayerTeamResponse& default_instance();

  void Swap(SetPlayerTeamResponse* other);

  // implements Message ----------------------------------------------

  inline SetPlayerTeamResponse* New() const { return New(NULL); }

  SetPlayerTeamResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SetPlayerTeamResponse& from);
  void MergeFrom(const SetPlayerTeamResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SetPlayerTeamResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef SetPlayerTeamResponse_Status Status;
  static const Status UNSET =
    SetPlayerTeamResponse_Status_UNSET;
  static const Status SUCCESS =
    SetPlayerTeamResponse_Status_SUCCESS;
  static const Status TEAM_ALREADY_SET =
    SetPlayerTeamResponse_Status_TEAM_ALREADY_SET;
  static const Status FAILURE =
    SetPlayerTeamResponse_Status_FAILURE;
  static inline bool Status_IsValid(int value) {
    return SetPlayerTeamResponse_Status_IsValid(value);
  }
  static const Status Status_MIN =
    SetPlayerTeamResponse_Status_Status_MIN;
  static const Status Status_MAX =
    SetPlayerTeamResponse_Status_Status_MAX;
  static const int Status_ARRAYSIZE =
    SetPlayerTeamResponse_Status_Status_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Status_descriptor() {
    return SetPlayerTeamResponse_Status_descriptor();
  }
  static inline const ::std::string& Status_Name(Status value) {
    return SetPlayerTeamResponse_Status_Name(value);
  }
  static inline bool Status_Parse(const ::std::string& name,
      Status* value) {
    return SetPlayerTeamResponse_Status_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .POGOProtos.Networking.Responses.SetPlayerTeamResponse.Status status = 1;
  void clear_status();
  static const int kStatusFieldNumber = 1;
  ::POGOProtos::Networking::Responses::SetPlayerTeamResponse_Status status() const;
  void set_status(::POGOProtos::Networking::Responses::SetPlayerTeamResponse_Status value);

  // optional .POGOProtos.Data.PlayerData player_data = 2;
  bool has_player_data() const;
  void clear_player_data();
  static const int kPlayerDataFieldNumber = 2;
  const ::POGOProtos::Data::PlayerData& player_data() const;
  ::POGOProtos::Data::PlayerData* mutable_player_data();
  ::POGOProtos::Data::PlayerData* release_player_data();
  void set_allocated_player_data(::POGOProtos::Data::PlayerData* player_data);

  // @@protoc_insertion_point(class_scope:POGOProtos.Networking.Responses.SetPlayerTeamResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::POGOProtos::Data::PlayerData* player_data_;
  int status_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_POGOProtos_2fNetworking_2fResponses_2fSetPlayerTeamResponse_2eproto();
  friend void protobuf_AssignDesc_POGOProtos_2fNetworking_2fResponses_2fSetPlayerTeamResponse_2eproto();
  friend void protobuf_ShutdownFile_POGOProtos_2fNetworking_2fResponses_2fSetPlayerTeamResponse_2eproto();

  void InitAsDefaultInstance();
  static SetPlayerTeamResponse* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// SetPlayerTeamResponse

// optional .POGOProtos.Networking.Responses.SetPlayerTeamResponse.Status status = 1;
inline void SetPlayerTeamResponse::clear_status() {
  status_ = 0;
}
inline ::POGOProtos::Networking::Responses::SetPlayerTeamResponse_Status SetPlayerTeamResponse::status() const {
  // @@protoc_insertion_point(field_get:POGOProtos.Networking.Responses.SetPlayerTeamResponse.status)
  return static_cast< ::POGOProtos::Networking::Responses::SetPlayerTeamResponse_Status >(status_);
}
inline void SetPlayerTeamResponse::set_status(::POGOProtos::Networking::Responses::SetPlayerTeamResponse_Status value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:POGOProtos.Networking.Responses.SetPlayerTeamResponse.status)
}

// optional .POGOProtos.Data.PlayerData player_data = 2;
inline bool SetPlayerTeamResponse::has_player_data() const {
  return !_is_default_instance_ && player_data_ != NULL;
}
inline void SetPlayerTeamResponse::clear_player_data() {
  if (GetArenaNoVirtual() == NULL && player_data_ != NULL) delete player_data_;
  player_data_ = NULL;
}
inline const ::POGOProtos::Data::PlayerData& SetPlayerTeamResponse::player_data() const {
  // @@protoc_insertion_point(field_get:POGOProtos.Networking.Responses.SetPlayerTeamResponse.player_data)
  return player_data_ != NULL ? *player_data_ : *default_instance_->player_data_;
}
inline ::POGOProtos::Data::PlayerData* SetPlayerTeamResponse::mutable_player_data() {
  
  if (player_data_ == NULL) {
    player_data_ = new ::POGOProtos::Data::PlayerData;
  }
  // @@protoc_insertion_point(field_mutable:POGOProtos.Networking.Responses.SetPlayerTeamResponse.player_data)
  return player_data_;
}
inline ::POGOProtos::Data::PlayerData* SetPlayerTeamResponse::release_player_data() {
  // @@protoc_insertion_point(field_release:POGOProtos.Networking.Responses.SetPlayerTeamResponse.player_data)
  
  ::POGOProtos::Data::PlayerData* temp = player_data_;
  player_data_ = NULL;
  return temp;
}
inline void SetPlayerTeamResponse::set_allocated_player_data(::POGOProtos::Data::PlayerData* player_data) {
  delete player_data_;
  player_data_ = player_data;
  if (player_data) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:POGOProtos.Networking.Responses.SetPlayerTeamResponse.player_data)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Responses
}  // namespace Networking
}  // namespace POGOProtos

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::POGOProtos::Networking::Responses::SetPlayerTeamResponse_Status> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::POGOProtos::Networking::Responses::SetPlayerTeamResponse_Status>() {
  return ::POGOProtos::Networking::Responses::SetPlayerTeamResponse_Status_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_POGOProtos_2fNetworking_2fResponses_2fSetPlayerTeamResponse_2eproto__INCLUDED
