// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Responses/StartGymBattleResponse.proto

#ifndef PROTOBUF_POGOProtos_2fNetworking_2fResponses_2fStartGymBattleResponse_2eproto__INCLUDED
#define PROTOBUF_POGOProtos_2fNetworking_2fResponses_2fStartGymBattleResponse_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "POGOProtos/Data/Battle/BattleLog.pb.h"
#include "POGOProtos/Data/Battle/BattleParticipant.pb.h"
// @@protoc_insertion_point(includes)

namespace POGOProtos {
namespace Networking {
namespace Responses {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_POGOProtos_2fNetworking_2fResponses_2fStartGymBattleResponse_2eproto();
void protobuf_AssignDesc_POGOProtos_2fNetworking_2fResponses_2fStartGymBattleResponse_2eproto();
void protobuf_ShutdownFile_POGOProtos_2fNetworking_2fResponses_2fStartGymBattleResponse_2eproto();

class StartGymBattleResponse;

enum StartGymBattleResponse_Result {
  StartGymBattleResponse_Result_UNSET = 0,
  StartGymBattleResponse_Result_SUCCESS = 1,
  StartGymBattleResponse_Result_ERROR_GYM_NOT_FOUND = 2,
  StartGymBattleResponse_Result_ERROR_GYM_NEUTRAL = 3,
  StartGymBattleResponse_Result_ERROR_GYM_WRONG_TEAM = 4,
  StartGymBattleResponse_Result_ERROR_GYM_EMPTY = 5,
  StartGymBattleResponse_Result_ERROR_INVALID_DEFENDER = 6,
  StartGymBattleResponse_Result_ERROR_TRAINING_INVALID_ATTACKER_COUNT = 7,
  StartGymBattleResponse_Result_ERROR_ALL_POKEMON_FAINTED = 8,
  StartGymBattleResponse_Result_ERROR_TOO_MANY_BATTLES = 9,
  StartGymBattleResponse_Result_ERROR_TOO_MANY_PLAYERS = 10,
  StartGymBattleResponse_Result_ERROR_GYM_BATTLE_LOCKOUT = 11,
  StartGymBattleResponse_Result_ERROR_PLAYER_BELOW_MINIMUM_LEVEL = 12,
  StartGymBattleResponse_Result_ERROR_NOT_IN_RANGE = 13,
  StartGymBattleResponse_Result_StartGymBattleResponse_Result_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  StartGymBattleResponse_Result_StartGymBattleResponse_Result_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool StartGymBattleResponse_Result_IsValid(int value);
const StartGymBattleResponse_Result StartGymBattleResponse_Result_Result_MIN = StartGymBattleResponse_Result_UNSET;
const StartGymBattleResponse_Result StartGymBattleResponse_Result_Result_MAX = StartGymBattleResponse_Result_ERROR_NOT_IN_RANGE;
const int StartGymBattleResponse_Result_Result_ARRAYSIZE = StartGymBattleResponse_Result_Result_MAX + 1;

const ::google::protobuf::EnumDescriptor* StartGymBattleResponse_Result_descriptor();
inline const ::std::string& StartGymBattleResponse_Result_Name(StartGymBattleResponse_Result value) {
  return ::google::protobuf::internal::NameOfEnum(
    StartGymBattleResponse_Result_descriptor(), value);
}
inline bool StartGymBattleResponse_Result_Parse(
    const ::std::string& name, StartGymBattleResponse_Result* value) {
  return ::google::protobuf::internal::ParseNamedEnum<StartGymBattleResponse_Result>(
    StartGymBattleResponse_Result_descriptor(), name, value);
}
// ===================================================================

class StartGymBattleResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:POGOProtos.Networking.Responses.StartGymBattleResponse) */ {
 public:
  StartGymBattleResponse();
  virtual ~StartGymBattleResponse();

  StartGymBattleResponse(const StartGymBattleResponse& from);

  inline StartGymBattleResponse& operator=(const StartGymBattleResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StartGymBattleResponse& default_instance();

  void Swap(StartGymBattleResponse* other);

  // implements Message ----------------------------------------------

  inline StartGymBattleResponse* New() const { return New(NULL); }

  StartGymBattleResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StartGymBattleResponse& from);
  void MergeFrom(const StartGymBattleResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(StartGymBattleResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef StartGymBattleResponse_Result Result;
  static const Result UNSET =
    StartGymBattleResponse_Result_UNSET;
  static const Result SUCCESS =
    StartGymBattleResponse_Result_SUCCESS;
  static const Result ERROR_GYM_NOT_FOUND =
    StartGymBattleResponse_Result_ERROR_GYM_NOT_FOUND;
  static const Result ERROR_GYM_NEUTRAL =
    StartGymBattleResponse_Result_ERROR_GYM_NEUTRAL;
  static const Result ERROR_GYM_WRONG_TEAM =
    StartGymBattleResponse_Result_ERROR_GYM_WRONG_TEAM;
  static const Result ERROR_GYM_EMPTY =
    StartGymBattleResponse_Result_ERROR_GYM_EMPTY;
  static const Result ERROR_INVALID_DEFENDER =
    StartGymBattleResponse_Result_ERROR_INVALID_DEFENDER;
  static const Result ERROR_TRAINING_INVALID_ATTACKER_COUNT =
    StartGymBattleResponse_Result_ERROR_TRAINING_INVALID_ATTACKER_COUNT;
  static const Result ERROR_ALL_POKEMON_FAINTED =
    StartGymBattleResponse_Result_ERROR_ALL_POKEMON_FAINTED;
  static const Result ERROR_TOO_MANY_BATTLES =
    StartGymBattleResponse_Result_ERROR_TOO_MANY_BATTLES;
  static const Result ERROR_TOO_MANY_PLAYERS =
    StartGymBattleResponse_Result_ERROR_TOO_MANY_PLAYERS;
  static const Result ERROR_GYM_BATTLE_LOCKOUT =
    StartGymBattleResponse_Result_ERROR_GYM_BATTLE_LOCKOUT;
  static const Result ERROR_PLAYER_BELOW_MINIMUM_LEVEL =
    StartGymBattleResponse_Result_ERROR_PLAYER_BELOW_MINIMUM_LEVEL;
  static const Result ERROR_NOT_IN_RANGE =
    StartGymBattleResponse_Result_ERROR_NOT_IN_RANGE;
  static inline bool Result_IsValid(int value) {
    return StartGymBattleResponse_Result_IsValid(value);
  }
  static const Result Result_MIN =
    StartGymBattleResponse_Result_Result_MIN;
  static const Result Result_MAX =
    StartGymBattleResponse_Result_Result_MAX;
  static const int Result_ARRAYSIZE =
    StartGymBattleResponse_Result_Result_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Result_descriptor() {
    return StartGymBattleResponse_Result_descriptor();
  }
  static inline const ::std::string& Result_Name(Result value) {
    return StartGymBattleResponse_Result_Name(value);
  }
  static inline bool Result_Parse(const ::std::string& name,
      Result* value) {
    return StartGymBattleResponse_Result_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .POGOProtos.Networking.Responses.StartGymBattleResponse.Result result = 1;
  void clear_result();
  static const int kResultFieldNumber = 1;
  ::POGOProtos::Networking::Responses::StartGymBattleResponse_Result result() const;
  void set_result(::POGOProtos::Networking::Responses::StartGymBattleResponse_Result value);

  // optional int64 battle_start_timestamp_ms = 2;
  void clear_battle_start_timestamp_ms();
  static const int kBattleStartTimestampMsFieldNumber = 2;
  ::google::protobuf::int64 battle_start_timestamp_ms() const;
  void set_battle_start_timestamp_ms(::google::protobuf::int64 value);

  // optional int64 battle_end_timestamp_ms = 3;
  void clear_battle_end_timestamp_ms();
  static const int kBattleEndTimestampMsFieldNumber = 3;
  ::google::protobuf::int64 battle_end_timestamp_ms() const;
  void set_battle_end_timestamp_ms(::google::protobuf::int64 value);

  // optional string battle_id = 4;
  void clear_battle_id();
  static const int kBattleIdFieldNumber = 4;
  const ::std::string& battle_id() const;
  void set_battle_id(const ::std::string& value);
  void set_battle_id(const char* value);
  void set_battle_id(const char* value, size_t size);
  ::std::string* mutable_battle_id();
  ::std::string* release_battle_id();
  void set_allocated_battle_id(::std::string* battle_id);

  // optional .POGOProtos.Data.Battle.BattleParticipant defender = 5;
  bool has_defender() const;
  void clear_defender();
  static const int kDefenderFieldNumber = 5;
  const ::POGOProtos::Data::Battle::BattleParticipant& defender() const;
  ::POGOProtos::Data::Battle::BattleParticipant* mutable_defender();
  ::POGOProtos::Data::Battle::BattleParticipant* release_defender();
  void set_allocated_defender(::POGOProtos::Data::Battle::BattleParticipant* defender);

  // optional .POGOProtos.Data.Battle.BattleLog battle_log = 6;
  bool has_battle_log() const;
  void clear_battle_log();
  static const int kBattleLogFieldNumber = 6;
  const ::POGOProtos::Data::Battle::BattleLog& battle_log() const;
  ::POGOProtos::Data::Battle::BattleLog* mutable_battle_log();
  ::POGOProtos::Data::Battle::BattleLog* release_battle_log();
  void set_allocated_battle_log(::POGOProtos::Data::Battle::BattleLog* battle_log);

  // @@protoc_insertion_point(class_scope:POGOProtos.Networking.Responses.StartGymBattleResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 battle_start_timestamp_ms_;
  ::google::protobuf::int64 battle_end_timestamp_ms_;
  ::google::protobuf::internal::ArenaStringPtr battle_id_;
  ::POGOProtos::Data::Battle::BattleParticipant* defender_;
  ::POGOProtos::Data::Battle::BattleLog* battle_log_;
  int result_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_POGOProtos_2fNetworking_2fResponses_2fStartGymBattleResponse_2eproto();
  friend void protobuf_AssignDesc_POGOProtos_2fNetworking_2fResponses_2fStartGymBattleResponse_2eproto();
  friend void protobuf_ShutdownFile_POGOProtos_2fNetworking_2fResponses_2fStartGymBattleResponse_2eproto();

  void InitAsDefaultInstance();
  static StartGymBattleResponse* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// StartGymBattleResponse

// optional .POGOProtos.Networking.Responses.StartGymBattleResponse.Result result = 1;
inline void StartGymBattleResponse::clear_result() {
  result_ = 0;
}
inline ::POGOProtos::Networking::Responses::StartGymBattleResponse_Result StartGymBattleResponse::result() const {
  // @@protoc_insertion_point(field_get:POGOProtos.Networking.Responses.StartGymBattleResponse.result)
  return static_cast< ::POGOProtos::Networking::Responses::StartGymBattleResponse_Result >(result_);
}
inline void StartGymBattleResponse::set_result(::POGOProtos::Networking::Responses::StartGymBattleResponse_Result value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:POGOProtos.Networking.Responses.StartGymBattleResponse.result)
}

// optional int64 battle_start_timestamp_ms = 2;
inline void StartGymBattleResponse::clear_battle_start_timestamp_ms() {
  battle_start_timestamp_ms_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 StartGymBattleResponse::battle_start_timestamp_ms() const {
  // @@protoc_insertion_point(field_get:POGOProtos.Networking.Responses.StartGymBattleResponse.battle_start_timestamp_ms)
  return battle_start_timestamp_ms_;
}
inline void StartGymBattleResponse::set_battle_start_timestamp_ms(::google::protobuf::int64 value) {
  
  battle_start_timestamp_ms_ = value;
  // @@protoc_insertion_point(field_set:POGOProtos.Networking.Responses.StartGymBattleResponse.battle_start_timestamp_ms)
}

// optional int64 battle_end_timestamp_ms = 3;
inline void StartGymBattleResponse::clear_battle_end_timestamp_ms() {
  battle_end_timestamp_ms_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 StartGymBattleResponse::battle_end_timestamp_ms() const {
  // @@protoc_insertion_point(field_get:POGOProtos.Networking.Responses.StartGymBattleResponse.battle_end_timestamp_ms)
  return battle_end_timestamp_ms_;
}
inline void StartGymBattleResponse::set_battle_end_timestamp_ms(::google::protobuf::int64 value) {
  
  battle_end_timestamp_ms_ = value;
  // @@protoc_insertion_point(field_set:POGOProtos.Networking.Responses.StartGymBattleResponse.battle_end_timestamp_ms)
}

// optional string battle_id = 4;
inline void StartGymBattleResponse::clear_battle_id() {
  battle_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& StartGymBattleResponse::battle_id() const {
  // @@protoc_insertion_point(field_get:POGOProtos.Networking.Responses.StartGymBattleResponse.battle_id)
  return battle_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StartGymBattleResponse::set_battle_id(const ::std::string& value) {
  
  battle_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:POGOProtos.Networking.Responses.StartGymBattleResponse.battle_id)
}
inline void StartGymBattleResponse::set_battle_id(const char* value) {
  
  battle_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:POGOProtos.Networking.Responses.StartGymBattleResponse.battle_id)
}
inline void StartGymBattleResponse::set_battle_id(const char* value, size_t size) {
  
  battle_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:POGOProtos.Networking.Responses.StartGymBattleResponse.battle_id)
}
inline ::std::string* StartGymBattleResponse::mutable_battle_id() {
  
  // @@protoc_insertion_point(field_mutable:POGOProtos.Networking.Responses.StartGymBattleResponse.battle_id)
  return battle_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* StartGymBattleResponse::release_battle_id() {
  // @@protoc_insertion_point(field_release:POGOProtos.Networking.Responses.StartGymBattleResponse.battle_id)
  
  return battle_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StartGymBattleResponse::set_allocated_battle_id(::std::string* battle_id) {
  if (battle_id != NULL) {
    
  } else {
    
  }
  battle_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), battle_id);
  // @@protoc_insertion_point(field_set_allocated:POGOProtos.Networking.Responses.StartGymBattleResponse.battle_id)
}

// optional .POGOProtos.Data.Battle.BattleParticipant defender = 5;
inline bool StartGymBattleResponse::has_defender() const {
  return !_is_default_instance_ && defender_ != NULL;
}
inline void StartGymBattleResponse::clear_defender() {
  if (GetArenaNoVirtual() == NULL && defender_ != NULL) delete defender_;
  defender_ = NULL;
}
inline const ::POGOProtos::Data::Battle::BattleParticipant& StartGymBattleResponse::defender() const {
  // @@protoc_insertion_point(field_get:POGOProtos.Networking.Responses.StartGymBattleResponse.defender)
  return defender_ != NULL ? *defender_ : *default_instance_->defender_;
}
inline ::POGOProtos::Data::Battle::BattleParticipant* StartGymBattleResponse::mutable_defender() {
  
  if (defender_ == NULL) {
    defender_ = new ::POGOProtos::Data::Battle::BattleParticipant;
  }
  // @@protoc_insertion_point(field_mutable:POGOProtos.Networking.Responses.StartGymBattleResponse.defender)
  return defender_;
}
inline ::POGOProtos::Data::Battle::BattleParticipant* StartGymBattleResponse::release_defender() {
  // @@protoc_insertion_point(field_release:POGOProtos.Networking.Responses.StartGymBattleResponse.defender)
  
  ::POGOProtos::Data::Battle::BattleParticipant* temp = defender_;
  defender_ = NULL;
  return temp;
}
inline void StartGymBattleResponse::set_allocated_defender(::POGOProtos::Data::Battle::BattleParticipant* defender) {
  delete defender_;
  defender_ = defender;
  if (defender) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:POGOProtos.Networking.Responses.StartGymBattleResponse.defender)
}

// optional .POGOProtos.Data.Battle.BattleLog battle_log = 6;
inline bool StartGymBattleResponse::has_battle_log() const {
  return !_is_default_instance_ && battle_log_ != NULL;
}
inline void StartGymBattleResponse::clear_battle_log() {
  if (GetArenaNoVirtual() == NULL && battle_log_ != NULL) delete battle_log_;
  battle_log_ = NULL;
}
inline const ::POGOProtos::Data::Battle::BattleLog& StartGymBattleResponse::battle_log() const {
  // @@protoc_insertion_point(field_get:POGOProtos.Networking.Responses.StartGymBattleResponse.battle_log)
  return battle_log_ != NULL ? *battle_log_ : *default_instance_->battle_log_;
}
inline ::POGOProtos::Data::Battle::BattleLog* StartGymBattleResponse::mutable_battle_log() {
  
  if (battle_log_ == NULL) {
    battle_log_ = new ::POGOProtos::Data::Battle::BattleLog;
  }
  // @@protoc_insertion_point(field_mutable:POGOProtos.Networking.Responses.StartGymBattleResponse.battle_log)
  return battle_log_;
}
inline ::POGOProtos::Data::Battle::BattleLog* StartGymBattleResponse::release_battle_log() {
  // @@protoc_insertion_point(field_release:POGOProtos.Networking.Responses.StartGymBattleResponse.battle_log)
  
  ::POGOProtos::Data::Battle::BattleLog* temp = battle_log_;
  battle_log_ = NULL;
  return temp;
}
inline void StartGymBattleResponse::set_allocated_battle_log(::POGOProtos::Data::Battle::BattleLog* battle_log) {
  delete battle_log_;
  battle_log_ = battle_log;
  if (battle_log) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:POGOProtos.Networking.Responses.StartGymBattleResponse.battle_log)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Responses
}  // namespace Networking
}  // namespace POGOProtos

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::POGOProtos::Networking::Responses::StartGymBattleResponse_Result> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::POGOProtos::Networking::Responses::StartGymBattleResponse_Result>() {
  return ::POGOProtos::Networking::Responses::StartGymBattleResponse_Result_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_POGOProtos_2fNetworking_2fResponses_2fStartGymBattleResponse_2eproto__INCLUDED
