// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Responses/UseItemReviveResponse.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "POGOProtos/Networking/Responses/UseItemReviveResponse.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace POGOProtos {
namespace Networking {
namespace Responses {

namespace {

const ::google::protobuf::Descriptor* UseItemReviveResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  UseItemReviveResponse_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* UseItemReviveResponse_Result_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_POGOProtos_2fNetworking_2fResponses_2fUseItemReviveResponse_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_POGOProtos_2fNetworking_2fResponses_2fUseItemReviveResponse_2eproto() {
  protobuf_AddDesc_POGOProtos_2fNetworking_2fResponses_2fUseItemReviveResponse_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "POGOProtos/Networking/Responses/UseItemReviveResponse.proto");
  GOOGLE_CHECK(file != NULL);
  UseItemReviveResponse_descriptor_ = file->message_type(0);
  static const int UseItemReviveResponse_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UseItemReviveResponse, result_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UseItemReviveResponse, stamina_),
  };
  UseItemReviveResponse_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      UseItemReviveResponse_descriptor_,
      UseItemReviveResponse::default_instance_,
      UseItemReviveResponse_offsets_,
      -1,
      -1,
      -1,
      sizeof(UseItemReviveResponse),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UseItemReviveResponse, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UseItemReviveResponse, _is_default_instance_));
  UseItemReviveResponse_Result_descriptor_ = UseItemReviveResponse_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_POGOProtos_2fNetworking_2fResponses_2fUseItemReviveResponse_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      UseItemReviveResponse_descriptor_, &UseItemReviveResponse::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_POGOProtos_2fNetworking_2fResponses_2fUseItemReviveResponse_2eproto() {
  delete UseItemReviveResponse::default_instance_;
  delete UseItemReviveResponse_reflection_;
}

void protobuf_AddDesc_POGOProtos_2fNetworking_2fResponses_2fUseItemReviveResponse_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_POGOProtos_2fNetworking_2fResponses_2fUseItemReviveResponse_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n;POGOProtos/Networking/Responses/UseIte"
    "mReviveResponse.proto\022\037POGOProtos.Networ"
    "king.Responses\"\341\001\n\025UseItemReviveResponse"
    "\022M\n\006result\030\001 \001(\0162=.POGOProtos.Networking"
    ".Responses.UseItemReviveResponse.Result\022"
    "\017\n\007stamina\030\002 \001(\005\"h\n\006Result\022\t\n\005UNSET\020\000\022\013\n"
    "\007SUCCESS\020\001\022\024\n\020ERROR_NO_POKEMON\020\002\022\024\n\020ERRO"
    "R_CANNOT_USE\020\003\022\032\n\026ERROR_DEPLOYED_TO_FORT"
    "\020\004b\006proto3", 330);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "POGOProtos/Networking/Responses/UseItemReviveResponse.proto", &protobuf_RegisterTypes);
  UseItemReviveResponse::default_instance_ = new UseItemReviveResponse();
  UseItemReviveResponse::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_POGOProtos_2fNetworking_2fResponses_2fUseItemReviveResponse_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_POGOProtos_2fNetworking_2fResponses_2fUseItemReviveResponse_2eproto {
  StaticDescriptorInitializer_POGOProtos_2fNetworking_2fResponses_2fUseItemReviveResponse_2eproto() {
    protobuf_AddDesc_POGOProtos_2fNetworking_2fResponses_2fUseItemReviveResponse_2eproto();
  }
} static_descriptor_initializer_POGOProtos_2fNetworking_2fResponses_2fUseItemReviveResponse_2eproto_;

// ===================================================================

const ::google::protobuf::EnumDescriptor* UseItemReviveResponse_Result_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return UseItemReviveResponse_Result_descriptor_;
}
bool UseItemReviveResponse_Result_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const UseItemReviveResponse_Result UseItemReviveResponse::UNSET;
const UseItemReviveResponse_Result UseItemReviveResponse::SUCCESS;
const UseItemReviveResponse_Result UseItemReviveResponse::ERROR_NO_POKEMON;
const UseItemReviveResponse_Result UseItemReviveResponse::ERROR_CANNOT_USE;
const UseItemReviveResponse_Result UseItemReviveResponse::ERROR_DEPLOYED_TO_FORT;
const UseItemReviveResponse_Result UseItemReviveResponse::Result_MIN;
const UseItemReviveResponse_Result UseItemReviveResponse::Result_MAX;
const int UseItemReviveResponse::Result_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int UseItemReviveResponse::kResultFieldNumber;
const int UseItemReviveResponse::kStaminaFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

UseItemReviveResponse::UseItemReviveResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:POGOProtos.Networking.Responses.UseItemReviveResponse)
}

void UseItemReviveResponse::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

UseItemReviveResponse::UseItemReviveResponse(const UseItemReviveResponse& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:POGOProtos.Networking.Responses.UseItemReviveResponse)
}

void UseItemReviveResponse::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  result_ = 0;
  stamina_ = 0;
}

UseItemReviveResponse::~UseItemReviveResponse() {
  // @@protoc_insertion_point(destructor:POGOProtos.Networking.Responses.UseItemReviveResponse)
  SharedDtor();
}

void UseItemReviveResponse::SharedDtor() {
  if (this != default_instance_) {
  }
}

void UseItemReviveResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* UseItemReviveResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return UseItemReviveResponse_descriptor_;
}

const UseItemReviveResponse& UseItemReviveResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_POGOProtos_2fNetworking_2fResponses_2fUseItemReviveResponse_2eproto();
  return *default_instance_;
}

UseItemReviveResponse* UseItemReviveResponse::default_instance_ = NULL;

UseItemReviveResponse* UseItemReviveResponse::New(::google::protobuf::Arena* arena) const {
  UseItemReviveResponse* n = new UseItemReviveResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void UseItemReviveResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:POGOProtos.Networking.Responses.UseItemReviveResponse)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(UseItemReviveResponse, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<UseItemReviveResponse*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(result_, stamina_);

#undef ZR_HELPER_
#undef ZR_

}

bool UseItemReviveResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:POGOProtos.Networking.Responses.UseItemReviveResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .POGOProtos.Networking.Responses.UseItemReviveResponse.Result result = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_result(static_cast< ::POGOProtos::Networking::Responses::UseItemReviveResponse_Result >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_stamina;
        break;
      }

      // optional int32 stamina = 2;
      case 2: {
        if (tag == 16) {
         parse_stamina:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &stamina_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:POGOProtos.Networking.Responses.UseItemReviveResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:POGOProtos.Networking.Responses.UseItemReviveResponse)
  return false;
#undef DO_
}

void UseItemReviveResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:POGOProtos.Networking.Responses.UseItemReviveResponse)
  // optional .POGOProtos.Networking.Responses.UseItemReviveResponse.Result result = 1;
  if (this->result() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->result(), output);
  }

  // optional int32 stamina = 2;
  if (this->stamina() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->stamina(), output);
  }

  // @@protoc_insertion_point(serialize_end:POGOProtos.Networking.Responses.UseItemReviveResponse)
}

::google::protobuf::uint8* UseItemReviveResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:POGOProtos.Networking.Responses.UseItemReviveResponse)
  // optional .POGOProtos.Networking.Responses.UseItemReviveResponse.Result result = 1;
  if (this->result() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->result(), target);
  }

  // optional int32 stamina = 2;
  if (this->stamina() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->stamina(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:POGOProtos.Networking.Responses.UseItemReviveResponse)
  return target;
}

int UseItemReviveResponse::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:POGOProtos.Networking.Responses.UseItemReviveResponse)
  int total_size = 0;

  // optional .POGOProtos.Networking.Responses.UseItemReviveResponse.Result result = 1;
  if (this->result() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->result());
  }

  // optional int32 stamina = 2;
  if (this->stamina() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->stamina());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void UseItemReviveResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:POGOProtos.Networking.Responses.UseItemReviveResponse)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const UseItemReviveResponse* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const UseItemReviveResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:POGOProtos.Networking.Responses.UseItemReviveResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:POGOProtos.Networking.Responses.UseItemReviveResponse)
    MergeFrom(*source);
  }
}

void UseItemReviveResponse::MergeFrom(const UseItemReviveResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:POGOProtos.Networking.Responses.UseItemReviveResponse)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.result() != 0) {
    set_result(from.result());
  }
  if (from.stamina() != 0) {
    set_stamina(from.stamina());
  }
}

void UseItemReviveResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:POGOProtos.Networking.Responses.UseItemReviveResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UseItemReviveResponse::CopyFrom(const UseItemReviveResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:POGOProtos.Networking.Responses.UseItemReviveResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UseItemReviveResponse::IsInitialized() const {

  return true;
}

void UseItemReviveResponse::Swap(UseItemReviveResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void UseItemReviveResponse::InternalSwap(UseItemReviveResponse* other) {
  std::swap(result_, other->result_);
  std::swap(stamina_, other->stamina_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata UseItemReviveResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = UseItemReviveResponse_descriptor_;
  metadata.reflection = UseItemReviveResponse_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// UseItemReviveResponse

// optional .POGOProtos.Networking.Responses.UseItemReviveResponse.Result result = 1;
void UseItemReviveResponse::clear_result() {
  result_ = 0;
}
 ::POGOProtos::Networking::Responses::UseItemReviveResponse_Result UseItemReviveResponse::result() const {
  // @@protoc_insertion_point(field_get:POGOProtos.Networking.Responses.UseItemReviveResponse.result)
  return static_cast< ::POGOProtos::Networking::Responses::UseItemReviveResponse_Result >(result_);
}
 void UseItemReviveResponse::set_result(::POGOProtos::Networking::Responses::UseItemReviveResponse_Result value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:POGOProtos.Networking.Responses.UseItemReviveResponse.result)
}

// optional int32 stamina = 2;
void UseItemReviveResponse::clear_stamina() {
  stamina_ = 0;
}
 ::google::protobuf::int32 UseItemReviveResponse::stamina() const {
  // @@protoc_insertion_point(field_get:POGOProtos.Networking.Responses.UseItemReviveResponse.stamina)
  return stamina_;
}
 void UseItemReviveResponse::set_stamina(::google::protobuf::int32 value) {
  
  stamina_ = value;
  // @@protoc_insertion_point(field_set:POGOProtos.Networking.Responses.UseItemReviveResponse.stamina)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Responses
}  // namespace Networking
}  // namespace POGOProtos

// @@protoc_insertion_point(global_scope)
