// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Inventory/AppliedItems.proto

#ifndef PROTOBUF_POGOProtos_2fInventory_2fAppliedItems_2eproto__INCLUDED
#define PROTOBUF_POGOProtos_2fInventory_2fAppliedItems_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "POGOProtos/Inventory/AppliedItem.pb.h"
// @@protoc_insertion_point(includes)

namespace POGOProtos {
namespace Inventory {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_POGOProtos_2fInventory_2fAppliedItems_2eproto();
void protobuf_AssignDesc_POGOProtos_2fInventory_2fAppliedItems_2eproto();
void protobuf_ShutdownFile_POGOProtos_2fInventory_2fAppliedItems_2eproto();

class AppliedItems;

// ===================================================================

class AppliedItems : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:POGOProtos.Inventory.AppliedItems) */ {
 public:
  AppliedItems();
  virtual ~AppliedItems();

  AppliedItems(const AppliedItems& from);

  inline AppliedItems& operator=(const AppliedItems& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AppliedItems& default_instance();

  void Swap(AppliedItems* other);

  // implements Message ----------------------------------------------

  inline AppliedItems* New() const { return New(NULL); }

  AppliedItems* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AppliedItems& from);
  void MergeFrom(const AppliedItems& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(AppliedItems* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .POGOProtos.Inventory.AppliedItem item = 4;
  int item_size() const;
  void clear_item();
  static const int kItemFieldNumber = 4;
  const ::POGOProtos::Inventory::AppliedItem& item(int index) const;
  ::POGOProtos::Inventory::AppliedItem* mutable_item(int index);
  ::POGOProtos::Inventory::AppliedItem* add_item();
  ::google::protobuf::RepeatedPtrField< ::POGOProtos::Inventory::AppliedItem >*
      mutable_item();
  const ::google::protobuf::RepeatedPtrField< ::POGOProtos::Inventory::AppliedItem >&
      item() const;

  // @@protoc_insertion_point(class_scope:POGOProtos.Inventory.AppliedItems)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::POGOProtos::Inventory::AppliedItem > item_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_POGOProtos_2fInventory_2fAppliedItems_2eproto();
  friend void protobuf_AssignDesc_POGOProtos_2fInventory_2fAppliedItems_2eproto();
  friend void protobuf_ShutdownFile_POGOProtos_2fInventory_2fAppliedItems_2eproto();

  void InitAsDefaultInstance();
  static AppliedItems* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// AppliedItems

// repeated .POGOProtos.Inventory.AppliedItem item = 4;
inline int AppliedItems::item_size() const {
  return item_.size();
}
inline void AppliedItems::clear_item() {
  item_.Clear();
}
inline const ::POGOProtos::Inventory::AppliedItem& AppliedItems::item(int index) const {
  // @@protoc_insertion_point(field_get:POGOProtos.Inventory.AppliedItems.item)
  return item_.Get(index);
}
inline ::POGOProtos::Inventory::AppliedItem* AppliedItems::mutable_item(int index) {
  // @@protoc_insertion_point(field_mutable:POGOProtos.Inventory.AppliedItems.item)
  return item_.Mutable(index);
}
inline ::POGOProtos::Inventory::AppliedItem* AppliedItems::add_item() {
  // @@protoc_insertion_point(field_add:POGOProtos.Inventory.AppliedItems.item)
  return item_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::POGOProtos::Inventory::AppliedItem >*
AppliedItems::mutable_item() {
  // @@protoc_insertion_point(field_mutable_list:POGOProtos.Inventory.AppliedItems.item)
  return &item_;
}
inline const ::google::protobuf::RepeatedPtrField< ::POGOProtos::Inventory::AppliedItem >&
AppliedItems::item() const {
  // @@protoc_insertion_point(field_list:POGOProtos.Inventory.AppliedItems.item)
  return item_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Inventory
}  // namespace POGOProtos

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_POGOProtos_2fInventory_2fAppliedItems_2eproto__INCLUDED
