// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Enums/PokemonFamilyId.proto

#ifndef PROTOBUF_POGOProtos_2fEnums_2fPokemonFamilyId_2eproto__INCLUDED
#define PROTOBUF_POGOProtos_2fEnums_2fPokemonFamilyId_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

namespace POGOProtos {
namespace Enums {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_POGOProtos_2fEnums_2fPokemonFamilyId_2eproto();
void protobuf_AssignDesc_POGOProtos_2fEnums_2fPokemonFamilyId_2eproto();
void protobuf_ShutdownFile_POGOProtos_2fEnums_2fPokemonFamilyId_2eproto();


enum PokemonFamilyId {
  FAMILY_UNSET = 0,
  FAMILY_BULBASAUR = 1,
  FAMILY_CHARMANDER = 4,
  FAMILY_SQUIRTLE = 7,
  FAMILY_CATERPIE = 10,
  FAMILY_WEEDLE = 13,
  FAMILY_PIDGEY = 16,
  FAMILY_RATTATA = 19,
  FAMILY_SPEAROW = 21,
  FAMILY_EKANS = 23,
  FAMILY_PIKACHU = 25,
  FAMILY_SANDSHREW = 27,
  FAMILY_NIDORAN_FEMALE = 29,
  FAMILY_NIDORAN_MALE = 32,
  FAMILY_CLEFAIRY = 35,
  FAMILY_VULPIX = 37,
  FAMILY_JIGGLYPUFF = 39,
  FAMILY_ZUBAT = 41,
  FAMILY_ODDISH = 43,
  FAMILY_PARAS = 46,
  FAMILY_VENONAT = 48,
  FAMILY_DIGLETT = 50,
  FAMILY_MEOWTH = 52,
  FAMILY_PSYDUCK = 54,
  FAMILY_MANKEY = 56,
  FAMILY_GROWLITHE = 58,
  FAMILY_POLIWAG = 60,
  FAMILY_ABRA = 63,
  FAMILY_MACHOP = 66,
  FAMILY_BELLSPROUT = 69,
  FAMILY_TENTACOOL = 72,
  FAMILY_GEODUDE = 74,
  FAMILY_PONYTA = 77,
  FAMILY_SLOWPOKE = 79,
  FAMILY_MAGNEMITE = 81,
  FAMILY_FARFETCHD = 83,
  FAMILY_DODUO = 84,
  FAMILY_SEEL = 86,
  FAMILY_GRIMER = 88,
  FAMILY_SHELLDER = 90,
  FAMILY_GASTLY = 92,
  FAMILY_ONIX = 95,
  FAMILY_DROWZEE = 96,
  FAMILY_HYPNO = 97,
  FAMILY_KRABBY = 98,
  FAMILY_VOLTORB = 100,
  FAMILY_EXEGGCUTE = 102,
  FAMILY_CUBONE = 104,
  FAMILY_HITMONLEE = 106,
  FAMILY_HITMONCHAN = 107,
  FAMILY_LICKITUNG = 108,
  FAMILY_KOFFING = 109,
  FAMILY_RHYHORN = 111,
  FAMILY_CHANSEY = 113,
  FAMILY_TANGELA = 114,
  FAMILY_KANGASKHAN = 115,
  FAMILY_HORSEA = 116,
  FAMILY_GOLDEEN = 118,
  FAMILY_STARYU = 120,
  FAMILY_MR_MIME = 122,
  FAMILY_SCYTHER = 123,
  FAMILY_JYNX = 124,
  FAMILY_ELECTABUZZ = 125,
  FAMILY_MAGMAR = 126,
  FAMILY_PINSIR = 127,
  FAMILY_TAUROS = 128,
  FAMILY_MAGIKARP = 129,
  FAMILY_LAPRAS = 131,
  FAMILY_DITTO = 132,
  FAMILY_EEVEE = 133,
  FAMILY_PORYGON = 137,
  FAMILY_OMANYTE = 138,
  FAMILY_KABUTO = 140,
  FAMILY_AERODACTYL = 142,
  FAMILY_SNORLAX = 143,
  FAMILY_ARTICUNO = 144,
  FAMILY_ZAPDOS = 145,
  FAMILY_MOLTRES = 146,
  FAMILY_DRATINI = 147,
  FAMILY_MEWTWO = 150,
  FAMILY_MEW = 151,
  PokemonFamilyId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  PokemonFamilyId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool PokemonFamilyId_IsValid(int value);
const PokemonFamilyId PokemonFamilyId_MIN = FAMILY_UNSET;
const PokemonFamilyId PokemonFamilyId_MAX = FAMILY_MEW;
const int PokemonFamilyId_ARRAYSIZE = PokemonFamilyId_MAX + 1;

const ::google::protobuf::EnumDescriptor* PokemonFamilyId_descriptor();
inline const ::std::string& PokemonFamilyId_Name(PokemonFamilyId value) {
  return ::google::protobuf::internal::NameOfEnum(
    PokemonFamilyId_descriptor(), value);
}
inline bool PokemonFamilyId_Parse(
    const ::std::string& name, PokemonFamilyId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PokemonFamilyId>(
    PokemonFamilyId_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Enums
}  // namespace POGOProtos

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::POGOProtos::Enums::PokemonFamilyId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::POGOProtos::Enums::PokemonFamilyId>() {
  return ::POGOProtos::Enums::PokemonFamilyId_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_POGOProtos_2fEnums_2fPokemonFamilyId_2eproto__INCLUDED
