// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Map/SpawnPoint.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "POGOProtos/Map/SpawnPoint.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace POGOProtos {
namespace Map {

namespace {

const ::google::protobuf::Descriptor* SpawnPoint_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SpawnPoint_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_POGOProtos_2fMap_2fSpawnPoint_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_POGOProtos_2fMap_2fSpawnPoint_2eproto() {
  protobuf_AddDesc_POGOProtos_2fMap_2fSpawnPoint_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "POGOProtos/Map/SpawnPoint.proto");
  GOOGLE_CHECK(file != NULL);
  SpawnPoint_descriptor_ = file->message_type(0);
  static const int SpawnPoint_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpawnPoint, latitude_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpawnPoint, longitude_),
  };
  SpawnPoint_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      SpawnPoint_descriptor_,
      SpawnPoint::default_instance_,
      SpawnPoint_offsets_,
      -1,
      -1,
      -1,
      sizeof(SpawnPoint),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpawnPoint, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpawnPoint, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_POGOProtos_2fMap_2fSpawnPoint_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      SpawnPoint_descriptor_, &SpawnPoint::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_POGOProtos_2fMap_2fSpawnPoint_2eproto() {
  delete SpawnPoint::default_instance_;
  delete SpawnPoint_reflection_;
}

void protobuf_AddDesc_POGOProtos_2fMap_2fSpawnPoint_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_POGOProtos_2fMap_2fSpawnPoint_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\037POGOProtos/Map/SpawnPoint.proto\022\016POGOP"
    "rotos.Map\"1\n\nSpawnPoint\022\020\n\010latitude\030\002 \001("
    "\001\022\021\n\tlongitude\030\003 \001(\001b\006proto3", 108);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "POGOProtos/Map/SpawnPoint.proto", &protobuf_RegisterTypes);
  SpawnPoint::default_instance_ = new SpawnPoint();
  SpawnPoint::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_POGOProtos_2fMap_2fSpawnPoint_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_POGOProtos_2fMap_2fSpawnPoint_2eproto {
  StaticDescriptorInitializer_POGOProtos_2fMap_2fSpawnPoint_2eproto() {
    protobuf_AddDesc_POGOProtos_2fMap_2fSpawnPoint_2eproto();
  }
} static_descriptor_initializer_POGOProtos_2fMap_2fSpawnPoint_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SpawnPoint::kLatitudeFieldNumber;
const int SpawnPoint::kLongitudeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SpawnPoint::SpawnPoint()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:POGOProtos.Map.SpawnPoint)
}

void SpawnPoint::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

SpawnPoint::SpawnPoint(const SpawnPoint& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:POGOProtos.Map.SpawnPoint)
}

void SpawnPoint::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  latitude_ = 0;
  longitude_ = 0;
}

SpawnPoint::~SpawnPoint() {
  // @@protoc_insertion_point(destructor:POGOProtos.Map.SpawnPoint)
  SharedDtor();
}

void SpawnPoint::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SpawnPoint::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SpawnPoint::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SpawnPoint_descriptor_;
}

const SpawnPoint& SpawnPoint::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_POGOProtos_2fMap_2fSpawnPoint_2eproto();
  return *default_instance_;
}

SpawnPoint* SpawnPoint::default_instance_ = NULL;

SpawnPoint* SpawnPoint::New(::google::protobuf::Arena* arena) const {
  SpawnPoint* n = new SpawnPoint;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SpawnPoint::Clear() {
// @@protoc_insertion_point(message_clear_start:POGOProtos.Map.SpawnPoint)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(SpawnPoint, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<SpawnPoint*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(latitude_, longitude_);

#undef ZR_HELPER_
#undef ZR_

}

bool SpawnPoint::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:POGOProtos.Map.SpawnPoint)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double latitude = 2;
      case 2: {
        if (tag == 17) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &latitude_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(25)) goto parse_longitude;
        break;
      }

      // optional double longitude = 3;
      case 3: {
        if (tag == 25) {
         parse_longitude:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &longitude_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:POGOProtos.Map.SpawnPoint)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:POGOProtos.Map.SpawnPoint)
  return false;
#undef DO_
}

void SpawnPoint::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:POGOProtos.Map.SpawnPoint)
  // optional double latitude = 2;
  if (this->latitude() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->latitude(), output);
  }

  // optional double longitude = 3;
  if (this->longitude() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->longitude(), output);
  }

  // @@protoc_insertion_point(serialize_end:POGOProtos.Map.SpawnPoint)
}

::google::protobuf::uint8* SpawnPoint::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:POGOProtos.Map.SpawnPoint)
  // optional double latitude = 2;
  if (this->latitude() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->latitude(), target);
  }

  // optional double longitude = 3;
  if (this->longitude() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->longitude(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:POGOProtos.Map.SpawnPoint)
  return target;
}

int SpawnPoint::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:POGOProtos.Map.SpawnPoint)
  int total_size = 0;

  // optional double latitude = 2;
  if (this->latitude() != 0) {
    total_size += 1 + 8;
  }

  // optional double longitude = 3;
  if (this->longitude() != 0) {
    total_size += 1 + 8;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SpawnPoint::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:POGOProtos.Map.SpawnPoint)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const SpawnPoint* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const SpawnPoint>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:POGOProtos.Map.SpawnPoint)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:POGOProtos.Map.SpawnPoint)
    MergeFrom(*source);
  }
}

void SpawnPoint::MergeFrom(const SpawnPoint& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:POGOProtos.Map.SpawnPoint)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.latitude() != 0) {
    set_latitude(from.latitude());
  }
  if (from.longitude() != 0) {
    set_longitude(from.longitude());
  }
}

void SpawnPoint::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:POGOProtos.Map.SpawnPoint)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SpawnPoint::CopyFrom(const SpawnPoint& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:POGOProtos.Map.SpawnPoint)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SpawnPoint::IsInitialized() const {

  return true;
}

void SpawnPoint::Swap(SpawnPoint* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SpawnPoint::InternalSwap(SpawnPoint* other) {
  std::swap(latitude_, other->latitude_);
  std::swap(longitude_, other->longitude_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SpawnPoint::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SpawnPoint_descriptor_;
  metadata.reflection = SpawnPoint_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SpawnPoint

// optional double latitude = 2;
void SpawnPoint::clear_latitude() {
  latitude_ = 0;
}
 double SpawnPoint::latitude() const {
  // @@protoc_insertion_point(field_get:POGOProtos.Map.SpawnPoint.latitude)
  return latitude_;
}
 void SpawnPoint::set_latitude(double value) {
  
  latitude_ = value;
  // @@protoc_insertion_point(field_set:POGOProtos.Map.SpawnPoint.latitude)
}

// optional double longitude = 3;
void SpawnPoint::clear_longitude() {
  longitude_ = 0;
}
 double SpawnPoint::longitude() const {
  // @@protoc_insertion_point(field_get:POGOProtos.Map.SpawnPoint.longitude)
  return longitude_;
}
 void SpawnPoint::set_longitude(double value) {
  
  longitude_ = value;
  // @@protoc_insertion_point(field_set:POGOProtos.Map.SpawnPoint.longitude)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Map
}  // namespace POGOProtos

// @@protoc_insertion_point(global_scope)
