// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Settings/Master/CameraSettings.proto

#ifndef PROTOBUF_POGOProtos_2fSettings_2fMaster_2fCameraSettings_2eproto__INCLUDED
#define PROTOBUF_POGOProtos_2fSettings_2fMaster_2fCameraSettings_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "POGOProtos/Enums/CameraTarget.pb.h"
#include "POGOProtos/Enums/CameraInterpolation.pb.h"
// @@protoc_insertion_point(includes)

namespace POGOProtos {
namespace Settings {
namespace Master {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_POGOProtos_2fSettings_2fMaster_2fCameraSettings_2eproto();
void protobuf_AssignDesc_POGOProtos_2fSettings_2fMaster_2fCameraSettings_2eproto();
void protobuf_ShutdownFile_POGOProtos_2fSettings_2fMaster_2fCameraSettings_2eproto();

class CameraSettings;

// ===================================================================

class CameraSettings : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:POGOProtos.Settings.Master.CameraSettings) */ {
 public:
  CameraSettings();
  virtual ~CameraSettings();

  CameraSettings(const CameraSettings& from);

  inline CameraSettings& operator=(const CameraSettings& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CameraSettings& default_instance();

  void Swap(CameraSettings* other);

  // implements Message ----------------------------------------------

  inline CameraSettings* New() const { return New(NULL); }

  CameraSettings* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CameraSettings& from);
  void MergeFrom(const CameraSettings& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CameraSettings* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string next_camera = 1;
  void clear_next_camera();
  static const int kNextCameraFieldNumber = 1;
  const ::std::string& next_camera() const;
  void set_next_camera(const ::std::string& value);
  void set_next_camera(const char* value);
  void set_next_camera(const char* value, size_t size);
  ::std::string* mutable_next_camera();
  ::std::string* release_next_camera();
  void set_allocated_next_camera(::std::string* next_camera);

  // repeated .POGOProtos.Enums.CameraInterpolation interpolation = 2;
  int interpolation_size() const;
  void clear_interpolation();
  static const int kInterpolationFieldNumber = 2;
  ::POGOProtos::Enums::CameraInterpolation interpolation(int index) const;
  void set_interpolation(int index, ::POGOProtos::Enums::CameraInterpolation value);
  void add_interpolation(::POGOProtos::Enums::CameraInterpolation value);
  const ::google::protobuf::RepeatedField<int>& interpolation() const;
  ::google::protobuf::RepeatedField<int>* mutable_interpolation();

  // repeated .POGOProtos.Enums.CameraTarget target_type = 3;
  int target_type_size() const;
  void clear_target_type();
  static const int kTargetTypeFieldNumber = 3;
  ::POGOProtos::Enums::CameraTarget target_type(int index) const;
  void set_target_type(int index, ::POGOProtos::Enums::CameraTarget value);
  void add_target_type(::POGOProtos::Enums::CameraTarget value);
  const ::google::protobuf::RepeatedField<int>& target_type() const;
  ::google::protobuf::RepeatedField<int>* mutable_target_type();

  // repeated float ease_in_speed = 4;
  int ease_in_speed_size() const;
  void clear_ease_in_speed();
  static const int kEaseInSpeedFieldNumber = 4;
  float ease_in_speed(int index) const;
  void set_ease_in_speed(int index, float value);
  void add_ease_in_speed(float value);
  const ::google::protobuf::RepeatedField< float >&
      ease_in_speed() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_ease_in_speed();

  // repeated float east_out_speed = 5;
  int east_out_speed_size() const;
  void clear_east_out_speed();
  static const int kEastOutSpeedFieldNumber = 5;
  float east_out_speed(int index) const;
  void set_east_out_speed(int index, float value);
  void add_east_out_speed(float value);
  const ::google::protobuf::RepeatedField< float >&
      east_out_speed() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_east_out_speed();

  // repeated float duration_seconds = 6;
  int duration_seconds_size() const;
  void clear_duration_seconds();
  static const int kDurationSecondsFieldNumber = 6;
  float duration_seconds(int index) const;
  void set_duration_seconds(int index, float value);
  void add_duration_seconds(float value);
  const ::google::protobuf::RepeatedField< float >&
      duration_seconds() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_duration_seconds();

  // repeated float wait_seconds = 7;
  int wait_seconds_size() const;
  void clear_wait_seconds();
  static const int kWaitSecondsFieldNumber = 7;
  float wait_seconds(int index) const;
  void set_wait_seconds(int index, float value);
  void add_wait_seconds(float value);
  const ::google::protobuf::RepeatedField< float >&
      wait_seconds() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_wait_seconds();

  // repeated float transition_seconds = 8;
  int transition_seconds_size() const;
  void clear_transition_seconds();
  static const int kTransitionSecondsFieldNumber = 8;
  float transition_seconds(int index) const;
  void set_transition_seconds(int index, float value);
  void add_transition_seconds(float value);
  const ::google::protobuf::RepeatedField< float >&
      transition_seconds() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_transition_seconds();

  // repeated float angle_degree = 9;
  int angle_degree_size() const;
  void clear_angle_degree();
  static const int kAngleDegreeFieldNumber = 9;
  float angle_degree(int index) const;
  void set_angle_degree(int index, float value);
  void add_angle_degree(float value);
  const ::google::protobuf::RepeatedField< float >&
      angle_degree() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_angle_degree();

  // repeated float angle_offset_degree = 10;
  int angle_offset_degree_size() const;
  void clear_angle_offset_degree();
  static const int kAngleOffsetDegreeFieldNumber = 10;
  float angle_offset_degree(int index) const;
  void set_angle_offset_degree(int index, float value);
  void add_angle_offset_degree(float value);
  const ::google::protobuf::RepeatedField< float >&
      angle_offset_degree() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_angle_offset_degree();

  // repeated float pitch_degree = 11;
  int pitch_degree_size() const;
  void clear_pitch_degree();
  static const int kPitchDegreeFieldNumber = 11;
  float pitch_degree(int index) const;
  void set_pitch_degree(int index, float value);
  void add_pitch_degree(float value);
  const ::google::protobuf::RepeatedField< float >&
      pitch_degree() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_pitch_degree();

  // repeated float pitch_offset_degree = 12;
  int pitch_offset_degree_size() const;
  void clear_pitch_offset_degree();
  static const int kPitchOffsetDegreeFieldNumber = 12;
  float pitch_offset_degree(int index) const;
  void set_pitch_offset_degree(int index, float value);
  void add_pitch_offset_degree(float value);
  const ::google::protobuf::RepeatedField< float >&
      pitch_offset_degree() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_pitch_offset_degree();

  // repeated float roll_degree = 13;
  int roll_degree_size() const;
  void clear_roll_degree();
  static const int kRollDegreeFieldNumber = 13;
  float roll_degree(int index) const;
  void set_roll_degree(int index, float value);
  void add_roll_degree(float value);
  const ::google::protobuf::RepeatedField< float >&
      roll_degree() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_roll_degree();

  // repeated float distance_meters = 14;
  int distance_meters_size() const;
  void clear_distance_meters();
  static const int kDistanceMetersFieldNumber = 14;
  float distance_meters(int index) const;
  void set_distance_meters(int index, float value);
  void add_distance_meters(float value);
  const ::google::protobuf::RepeatedField< float >&
      distance_meters() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_distance_meters();

  // repeated float height_percent = 15;
  int height_percent_size() const;
  void clear_height_percent();
  static const int kHeightPercentFieldNumber = 15;
  float height_percent(int index) const;
  void set_height_percent(int index, float value);
  void add_height_percent(float value);
  const ::google::protobuf::RepeatedField< float >&
      height_percent() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_height_percent();

  // repeated float vert_ctr_ratio = 16;
  int vert_ctr_ratio_size() const;
  void clear_vert_ctr_ratio();
  static const int kVertCtrRatioFieldNumber = 16;
  float vert_ctr_ratio(int index) const;
  void set_vert_ctr_ratio(int index, float value);
  void add_vert_ctr_ratio(float value);
  const ::google::protobuf::RepeatedField< float >&
      vert_ctr_ratio() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_vert_ctr_ratio();

  // @@protoc_insertion_point(class_scope:POGOProtos.Settings.Master.CameraSettings)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr next_camera_;
  ::google::protobuf::RepeatedField<int> interpolation_;
  mutable int _interpolation_cached_byte_size_;
  ::google::protobuf::RepeatedField<int> target_type_;
  mutable int _target_type_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > ease_in_speed_;
  mutable int _ease_in_speed_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > east_out_speed_;
  mutable int _east_out_speed_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > duration_seconds_;
  mutable int _duration_seconds_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > wait_seconds_;
  mutable int _wait_seconds_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > transition_seconds_;
  mutable int _transition_seconds_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > angle_degree_;
  mutable int _angle_degree_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > angle_offset_degree_;
  mutable int _angle_offset_degree_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > pitch_degree_;
  mutable int _pitch_degree_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > pitch_offset_degree_;
  mutable int _pitch_offset_degree_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > roll_degree_;
  mutable int _roll_degree_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > distance_meters_;
  mutable int _distance_meters_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > height_percent_;
  mutable int _height_percent_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > vert_ctr_ratio_;
  mutable int _vert_ctr_ratio_cached_byte_size_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_POGOProtos_2fSettings_2fMaster_2fCameraSettings_2eproto();
  friend void protobuf_AssignDesc_POGOProtos_2fSettings_2fMaster_2fCameraSettings_2eproto();
  friend void protobuf_ShutdownFile_POGOProtos_2fSettings_2fMaster_2fCameraSettings_2eproto();

  void InitAsDefaultInstance();
  static CameraSettings* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CameraSettings

// optional string next_camera = 1;
inline void CameraSettings::clear_next_camera() {
  next_camera_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CameraSettings::next_camera() const {
  // @@protoc_insertion_point(field_get:POGOProtos.Settings.Master.CameraSettings.next_camera)
  return next_camera_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CameraSettings::set_next_camera(const ::std::string& value) {
  
  next_camera_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:POGOProtos.Settings.Master.CameraSettings.next_camera)
}
inline void CameraSettings::set_next_camera(const char* value) {
  
  next_camera_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:POGOProtos.Settings.Master.CameraSettings.next_camera)
}
inline void CameraSettings::set_next_camera(const char* value, size_t size) {
  
  next_camera_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:POGOProtos.Settings.Master.CameraSettings.next_camera)
}
inline ::std::string* CameraSettings::mutable_next_camera() {
  
  // @@protoc_insertion_point(field_mutable:POGOProtos.Settings.Master.CameraSettings.next_camera)
  return next_camera_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CameraSettings::release_next_camera() {
  // @@protoc_insertion_point(field_release:POGOProtos.Settings.Master.CameraSettings.next_camera)
  
  return next_camera_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CameraSettings::set_allocated_next_camera(::std::string* next_camera) {
  if (next_camera != NULL) {
    
  } else {
    
  }
  next_camera_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), next_camera);
  // @@protoc_insertion_point(field_set_allocated:POGOProtos.Settings.Master.CameraSettings.next_camera)
}

// repeated .POGOProtos.Enums.CameraInterpolation interpolation = 2;
inline int CameraSettings::interpolation_size() const {
  return interpolation_.size();
}
inline void CameraSettings::clear_interpolation() {
  interpolation_.Clear();
}
inline ::POGOProtos::Enums::CameraInterpolation CameraSettings::interpolation(int index) const {
  // @@protoc_insertion_point(field_get:POGOProtos.Settings.Master.CameraSettings.interpolation)
  return static_cast< ::POGOProtos::Enums::CameraInterpolation >(interpolation_.Get(index));
}
inline void CameraSettings::set_interpolation(int index, ::POGOProtos::Enums::CameraInterpolation value) {
  interpolation_.Set(index, value);
  // @@protoc_insertion_point(field_set:POGOProtos.Settings.Master.CameraSettings.interpolation)
}
inline void CameraSettings::add_interpolation(::POGOProtos::Enums::CameraInterpolation value) {
  interpolation_.Add(value);
  // @@protoc_insertion_point(field_add:POGOProtos.Settings.Master.CameraSettings.interpolation)
}
inline const ::google::protobuf::RepeatedField<int>&
CameraSettings::interpolation() const {
  // @@protoc_insertion_point(field_list:POGOProtos.Settings.Master.CameraSettings.interpolation)
  return interpolation_;
}
inline ::google::protobuf::RepeatedField<int>*
CameraSettings::mutable_interpolation() {
  // @@protoc_insertion_point(field_mutable_list:POGOProtos.Settings.Master.CameraSettings.interpolation)
  return &interpolation_;
}

// repeated .POGOProtos.Enums.CameraTarget target_type = 3;
inline int CameraSettings::target_type_size() const {
  return target_type_.size();
}
inline void CameraSettings::clear_target_type() {
  target_type_.Clear();
}
inline ::POGOProtos::Enums::CameraTarget CameraSettings::target_type(int index) const {
  // @@protoc_insertion_point(field_get:POGOProtos.Settings.Master.CameraSettings.target_type)
  return static_cast< ::POGOProtos::Enums::CameraTarget >(target_type_.Get(index));
}
inline void CameraSettings::set_target_type(int index, ::POGOProtos::Enums::CameraTarget value) {
  target_type_.Set(index, value);
  // @@protoc_insertion_point(field_set:POGOProtos.Settings.Master.CameraSettings.target_type)
}
inline void CameraSettings::add_target_type(::POGOProtos::Enums::CameraTarget value) {
  target_type_.Add(value);
  // @@protoc_insertion_point(field_add:POGOProtos.Settings.Master.CameraSettings.target_type)
}
inline const ::google::protobuf::RepeatedField<int>&
CameraSettings::target_type() const {
  // @@protoc_insertion_point(field_list:POGOProtos.Settings.Master.CameraSettings.target_type)
  return target_type_;
}
inline ::google::protobuf::RepeatedField<int>*
CameraSettings::mutable_target_type() {
  // @@protoc_insertion_point(field_mutable_list:POGOProtos.Settings.Master.CameraSettings.target_type)
  return &target_type_;
}

// repeated float ease_in_speed = 4;
inline int CameraSettings::ease_in_speed_size() const {
  return ease_in_speed_.size();
}
inline void CameraSettings::clear_ease_in_speed() {
  ease_in_speed_.Clear();
}
inline float CameraSettings::ease_in_speed(int index) const {
  // @@protoc_insertion_point(field_get:POGOProtos.Settings.Master.CameraSettings.ease_in_speed)
  return ease_in_speed_.Get(index);
}
inline void CameraSettings::set_ease_in_speed(int index, float value) {
  ease_in_speed_.Set(index, value);
  // @@protoc_insertion_point(field_set:POGOProtos.Settings.Master.CameraSettings.ease_in_speed)
}
inline void CameraSettings::add_ease_in_speed(float value) {
  ease_in_speed_.Add(value);
  // @@protoc_insertion_point(field_add:POGOProtos.Settings.Master.CameraSettings.ease_in_speed)
}
inline const ::google::protobuf::RepeatedField< float >&
CameraSettings::ease_in_speed() const {
  // @@protoc_insertion_point(field_list:POGOProtos.Settings.Master.CameraSettings.ease_in_speed)
  return ease_in_speed_;
}
inline ::google::protobuf::RepeatedField< float >*
CameraSettings::mutable_ease_in_speed() {
  // @@protoc_insertion_point(field_mutable_list:POGOProtos.Settings.Master.CameraSettings.ease_in_speed)
  return &ease_in_speed_;
}

// repeated float east_out_speed = 5;
inline int CameraSettings::east_out_speed_size() const {
  return east_out_speed_.size();
}
inline void CameraSettings::clear_east_out_speed() {
  east_out_speed_.Clear();
}
inline float CameraSettings::east_out_speed(int index) const {
  // @@protoc_insertion_point(field_get:POGOProtos.Settings.Master.CameraSettings.east_out_speed)
  return east_out_speed_.Get(index);
}
inline void CameraSettings::set_east_out_speed(int index, float value) {
  east_out_speed_.Set(index, value);
  // @@protoc_insertion_point(field_set:POGOProtos.Settings.Master.CameraSettings.east_out_speed)
}
inline void CameraSettings::add_east_out_speed(float value) {
  east_out_speed_.Add(value);
  // @@protoc_insertion_point(field_add:POGOProtos.Settings.Master.CameraSettings.east_out_speed)
}
inline const ::google::protobuf::RepeatedField< float >&
CameraSettings::east_out_speed() const {
  // @@protoc_insertion_point(field_list:POGOProtos.Settings.Master.CameraSettings.east_out_speed)
  return east_out_speed_;
}
inline ::google::protobuf::RepeatedField< float >*
CameraSettings::mutable_east_out_speed() {
  // @@protoc_insertion_point(field_mutable_list:POGOProtos.Settings.Master.CameraSettings.east_out_speed)
  return &east_out_speed_;
}

// repeated float duration_seconds = 6;
inline int CameraSettings::duration_seconds_size() const {
  return duration_seconds_.size();
}
inline void CameraSettings::clear_duration_seconds() {
  duration_seconds_.Clear();
}
inline float CameraSettings::duration_seconds(int index) const {
  // @@protoc_insertion_point(field_get:POGOProtos.Settings.Master.CameraSettings.duration_seconds)
  return duration_seconds_.Get(index);
}
inline void CameraSettings::set_duration_seconds(int index, float value) {
  duration_seconds_.Set(index, value);
  // @@protoc_insertion_point(field_set:POGOProtos.Settings.Master.CameraSettings.duration_seconds)
}
inline void CameraSettings::add_duration_seconds(float value) {
  duration_seconds_.Add(value);
  // @@protoc_insertion_point(field_add:POGOProtos.Settings.Master.CameraSettings.duration_seconds)
}
inline const ::google::protobuf::RepeatedField< float >&
CameraSettings::duration_seconds() const {
  // @@protoc_insertion_point(field_list:POGOProtos.Settings.Master.CameraSettings.duration_seconds)
  return duration_seconds_;
}
inline ::google::protobuf::RepeatedField< float >*
CameraSettings::mutable_duration_seconds() {
  // @@protoc_insertion_point(field_mutable_list:POGOProtos.Settings.Master.CameraSettings.duration_seconds)
  return &duration_seconds_;
}

// repeated float wait_seconds = 7;
inline int CameraSettings::wait_seconds_size() const {
  return wait_seconds_.size();
}
inline void CameraSettings::clear_wait_seconds() {
  wait_seconds_.Clear();
}
inline float CameraSettings::wait_seconds(int index) const {
  // @@protoc_insertion_point(field_get:POGOProtos.Settings.Master.CameraSettings.wait_seconds)
  return wait_seconds_.Get(index);
}
inline void CameraSettings::set_wait_seconds(int index, float value) {
  wait_seconds_.Set(index, value);
  // @@protoc_insertion_point(field_set:POGOProtos.Settings.Master.CameraSettings.wait_seconds)
}
inline void CameraSettings::add_wait_seconds(float value) {
  wait_seconds_.Add(value);
  // @@protoc_insertion_point(field_add:POGOProtos.Settings.Master.CameraSettings.wait_seconds)
}
inline const ::google::protobuf::RepeatedField< float >&
CameraSettings::wait_seconds() const {
  // @@protoc_insertion_point(field_list:POGOProtos.Settings.Master.CameraSettings.wait_seconds)
  return wait_seconds_;
}
inline ::google::protobuf::RepeatedField< float >*
CameraSettings::mutable_wait_seconds() {
  // @@protoc_insertion_point(field_mutable_list:POGOProtos.Settings.Master.CameraSettings.wait_seconds)
  return &wait_seconds_;
}

// repeated float transition_seconds = 8;
inline int CameraSettings::transition_seconds_size() const {
  return transition_seconds_.size();
}
inline void CameraSettings::clear_transition_seconds() {
  transition_seconds_.Clear();
}
inline float CameraSettings::transition_seconds(int index) const {
  // @@protoc_insertion_point(field_get:POGOProtos.Settings.Master.CameraSettings.transition_seconds)
  return transition_seconds_.Get(index);
}
inline void CameraSettings::set_transition_seconds(int index, float value) {
  transition_seconds_.Set(index, value);
  // @@protoc_insertion_point(field_set:POGOProtos.Settings.Master.CameraSettings.transition_seconds)
}
inline void CameraSettings::add_transition_seconds(float value) {
  transition_seconds_.Add(value);
  // @@protoc_insertion_point(field_add:POGOProtos.Settings.Master.CameraSettings.transition_seconds)
}
inline const ::google::protobuf::RepeatedField< float >&
CameraSettings::transition_seconds() const {
  // @@protoc_insertion_point(field_list:POGOProtos.Settings.Master.CameraSettings.transition_seconds)
  return transition_seconds_;
}
inline ::google::protobuf::RepeatedField< float >*
CameraSettings::mutable_transition_seconds() {
  // @@protoc_insertion_point(field_mutable_list:POGOProtos.Settings.Master.CameraSettings.transition_seconds)
  return &transition_seconds_;
}

// repeated float angle_degree = 9;
inline int CameraSettings::angle_degree_size() const {
  return angle_degree_.size();
}
inline void CameraSettings::clear_angle_degree() {
  angle_degree_.Clear();
}
inline float CameraSettings::angle_degree(int index) const {
  // @@protoc_insertion_point(field_get:POGOProtos.Settings.Master.CameraSettings.angle_degree)
  return angle_degree_.Get(index);
}
inline void CameraSettings::set_angle_degree(int index, float value) {
  angle_degree_.Set(index, value);
  // @@protoc_insertion_point(field_set:POGOProtos.Settings.Master.CameraSettings.angle_degree)
}
inline void CameraSettings::add_angle_degree(float value) {
  angle_degree_.Add(value);
  // @@protoc_insertion_point(field_add:POGOProtos.Settings.Master.CameraSettings.angle_degree)
}
inline const ::google::protobuf::RepeatedField< float >&
CameraSettings::angle_degree() const {
  // @@protoc_insertion_point(field_list:POGOProtos.Settings.Master.CameraSettings.angle_degree)
  return angle_degree_;
}
inline ::google::protobuf::RepeatedField< float >*
CameraSettings::mutable_angle_degree() {
  // @@protoc_insertion_point(field_mutable_list:POGOProtos.Settings.Master.CameraSettings.angle_degree)
  return &angle_degree_;
}

// repeated float angle_offset_degree = 10;
inline int CameraSettings::angle_offset_degree_size() const {
  return angle_offset_degree_.size();
}
inline void CameraSettings::clear_angle_offset_degree() {
  angle_offset_degree_.Clear();
}
inline float CameraSettings::angle_offset_degree(int index) const {
  // @@protoc_insertion_point(field_get:POGOProtos.Settings.Master.CameraSettings.angle_offset_degree)
  return angle_offset_degree_.Get(index);
}
inline void CameraSettings::set_angle_offset_degree(int index, float value) {
  angle_offset_degree_.Set(index, value);
  // @@protoc_insertion_point(field_set:POGOProtos.Settings.Master.CameraSettings.angle_offset_degree)
}
inline void CameraSettings::add_angle_offset_degree(float value) {
  angle_offset_degree_.Add(value);
  // @@protoc_insertion_point(field_add:POGOProtos.Settings.Master.CameraSettings.angle_offset_degree)
}
inline const ::google::protobuf::RepeatedField< float >&
CameraSettings::angle_offset_degree() const {
  // @@protoc_insertion_point(field_list:POGOProtos.Settings.Master.CameraSettings.angle_offset_degree)
  return angle_offset_degree_;
}
inline ::google::protobuf::RepeatedField< float >*
CameraSettings::mutable_angle_offset_degree() {
  // @@protoc_insertion_point(field_mutable_list:POGOProtos.Settings.Master.CameraSettings.angle_offset_degree)
  return &angle_offset_degree_;
}

// repeated float pitch_degree = 11;
inline int CameraSettings::pitch_degree_size() const {
  return pitch_degree_.size();
}
inline void CameraSettings::clear_pitch_degree() {
  pitch_degree_.Clear();
}
inline float CameraSettings::pitch_degree(int index) const {
  // @@protoc_insertion_point(field_get:POGOProtos.Settings.Master.CameraSettings.pitch_degree)
  return pitch_degree_.Get(index);
}
inline void CameraSettings::set_pitch_degree(int index, float value) {
  pitch_degree_.Set(index, value);
  // @@protoc_insertion_point(field_set:POGOProtos.Settings.Master.CameraSettings.pitch_degree)
}
inline void CameraSettings::add_pitch_degree(float value) {
  pitch_degree_.Add(value);
  // @@protoc_insertion_point(field_add:POGOProtos.Settings.Master.CameraSettings.pitch_degree)
}
inline const ::google::protobuf::RepeatedField< float >&
CameraSettings::pitch_degree() const {
  // @@protoc_insertion_point(field_list:POGOProtos.Settings.Master.CameraSettings.pitch_degree)
  return pitch_degree_;
}
inline ::google::protobuf::RepeatedField< float >*
CameraSettings::mutable_pitch_degree() {
  // @@protoc_insertion_point(field_mutable_list:POGOProtos.Settings.Master.CameraSettings.pitch_degree)
  return &pitch_degree_;
}

// repeated float pitch_offset_degree = 12;
inline int CameraSettings::pitch_offset_degree_size() const {
  return pitch_offset_degree_.size();
}
inline void CameraSettings::clear_pitch_offset_degree() {
  pitch_offset_degree_.Clear();
}
inline float CameraSettings::pitch_offset_degree(int index) const {
  // @@protoc_insertion_point(field_get:POGOProtos.Settings.Master.CameraSettings.pitch_offset_degree)
  return pitch_offset_degree_.Get(index);
}
inline void CameraSettings::set_pitch_offset_degree(int index, float value) {
  pitch_offset_degree_.Set(index, value);
  // @@protoc_insertion_point(field_set:POGOProtos.Settings.Master.CameraSettings.pitch_offset_degree)
}
inline void CameraSettings::add_pitch_offset_degree(float value) {
  pitch_offset_degree_.Add(value);
  // @@protoc_insertion_point(field_add:POGOProtos.Settings.Master.CameraSettings.pitch_offset_degree)
}
inline const ::google::protobuf::RepeatedField< float >&
CameraSettings::pitch_offset_degree() const {
  // @@protoc_insertion_point(field_list:POGOProtos.Settings.Master.CameraSettings.pitch_offset_degree)
  return pitch_offset_degree_;
}
inline ::google::protobuf::RepeatedField< float >*
CameraSettings::mutable_pitch_offset_degree() {
  // @@protoc_insertion_point(field_mutable_list:POGOProtos.Settings.Master.CameraSettings.pitch_offset_degree)
  return &pitch_offset_degree_;
}

// repeated float roll_degree = 13;
inline int CameraSettings::roll_degree_size() const {
  return roll_degree_.size();
}
inline void CameraSettings::clear_roll_degree() {
  roll_degree_.Clear();
}
inline float CameraSettings::roll_degree(int index) const {
  // @@protoc_insertion_point(field_get:POGOProtos.Settings.Master.CameraSettings.roll_degree)
  return roll_degree_.Get(index);
}
inline void CameraSettings::set_roll_degree(int index, float value) {
  roll_degree_.Set(index, value);
  // @@protoc_insertion_point(field_set:POGOProtos.Settings.Master.CameraSettings.roll_degree)
}
inline void CameraSettings::add_roll_degree(float value) {
  roll_degree_.Add(value);
  // @@protoc_insertion_point(field_add:POGOProtos.Settings.Master.CameraSettings.roll_degree)
}
inline const ::google::protobuf::RepeatedField< float >&
CameraSettings::roll_degree() const {
  // @@protoc_insertion_point(field_list:POGOProtos.Settings.Master.CameraSettings.roll_degree)
  return roll_degree_;
}
inline ::google::protobuf::RepeatedField< float >*
CameraSettings::mutable_roll_degree() {
  // @@protoc_insertion_point(field_mutable_list:POGOProtos.Settings.Master.CameraSettings.roll_degree)
  return &roll_degree_;
}

// repeated float distance_meters = 14;
inline int CameraSettings::distance_meters_size() const {
  return distance_meters_.size();
}
inline void CameraSettings::clear_distance_meters() {
  distance_meters_.Clear();
}
inline float CameraSettings::distance_meters(int index) const {
  // @@protoc_insertion_point(field_get:POGOProtos.Settings.Master.CameraSettings.distance_meters)
  return distance_meters_.Get(index);
}
inline void CameraSettings::set_distance_meters(int index, float value) {
  distance_meters_.Set(index, value);
  // @@protoc_insertion_point(field_set:POGOProtos.Settings.Master.CameraSettings.distance_meters)
}
inline void CameraSettings::add_distance_meters(float value) {
  distance_meters_.Add(value);
  // @@protoc_insertion_point(field_add:POGOProtos.Settings.Master.CameraSettings.distance_meters)
}
inline const ::google::protobuf::RepeatedField< float >&
CameraSettings::distance_meters() const {
  // @@protoc_insertion_point(field_list:POGOProtos.Settings.Master.CameraSettings.distance_meters)
  return distance_meters_;
}
inline ::google::protobuf::RepeatedField< float >*
CameraSettings::mutable_distance_meters() {
  // @@protoc_insertion_point(field_mutable_list:POGOProtos.Settings.Master.CameraSettings.distance_meters)
  return &distance_meters_;
}

// repeated float height_percent = 15;
inline int CameraSettings::height_percent_size() const {
  return height_percent_.size();
}
inline void CameraSettings::clear_height_percent() {
  height_percent_.Clear();
}
inline float CameraSettings::height_percent(int index) const {
  // @@protoc_insertion_point(field_get:POGOProtos.Settings.Master.CameraSettings.height_percent)
  return height_percent_.Get(index);
}
inline void CameraSettings::set_height_percent(int index, float value) {
  height_percent_.Set(index, value);
  // @@protoc_insertion_point(field_set:POGOProtos.Settings.Master.CameraSettings.height_percent)
}
inline void CameraSettings::add_height_percent(float value) {
  height_percent_.Add(value);
  // @@protoc_insertion_point(field_add:POGOProtos.Settings.Master.CameraSettings.height_percent)
}
inline const ::google::protobuf::RepeatedField< float >&
CameraSettings::height_percent() const {
  // @@protoc_insertion_point(field_list:POGOProtos.Settings.Master.CameraSettings.height_percent)
  return height_percent_;
}
inline ::google::protobuf::RepeatedField< float >*
CameraSettings::mutable_height_percent() {
  // @@protoc_insertion_point(field_mutable_list:POGOProtos.Settings.Master.CameraSettings.height_percent)
  return &height_percent_;
}

// repeated float vert_ctr_ratio = 16;
inline int CameraSettings::vert_ctr_ratio_size() const {
  return vert_ctr_ratio_.size();
}
inline void CameraSettings::clear_vert_ctr_ratio() {
  vert_ctr_ratio_.Clear();
}
inline float CameraSettings::vert_ctr_ratio(int index) const {
  // @@protoc_insertion_point(field_get:POGOProtos.Settings.Master.CameraSettings.vert_ctr_ratio)
  return vert_ctr_ratio_.Get(index);
}
inline void CameraSettings::set_vert_ctr_ratio(int index, float value) {
  vert_ctr_ratio_.Set(index, value);
  // @@protoc_insertion_point(field_set:POGOProtos.Settings.Master.CameraSettings.vert_ctr_ratio)
}
inline void CameraSettings::add_vert_ctr_ratio(float value) {
  vert_ctr_ratio_.Add(value);
  // @@protoc_insertion_point(field_add:POGOProtos.Settings.Master.CameraSettings.vert_ctr_ratio)
}
inline const ::google::protobuf::RepeatedField< float >&
CameraSettings::vert_ctr_ratio() const {
  // @@protoc_insertion_point(field_list:POGOProtos.Settings.Master.CameraSettings.vert_ctr_ratio)
  return vert_ctr_ratio_;
}
inline ::google::protobuf::RepeatedField< float >*
CameraSettings::mutable_vert_ctr_ratio() {
  // @@protoc_insertion_point(field_mutable_list:POGOProtos.Settings.Master.CameraSettings.vert_ctr_ratio)
  return &vert_ctr_ratio_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Master
}  // namespace Settings
}  // namespace POGOProtos

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_POGOProtos_2fSettings_2fMaster_2fCameraSettings_2eproto__INCLUDED
