// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Settings/Master/MoveSequenceSettings.proto

#ifndef PROTOBUF_POGOProtos_2fSettings_2fMaster_2fMoveSequenceSettings_2eproto__INCLUDED
#define PROTOBUF_POGOProtos_2fSettings_2fMaster_2fMoveSequenceSettings_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace POGOProtos {
namespace Settings {
namespace Master {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_POGOProtos_2fSettings_2fMaster_2fMoveSequenceSettings_2eproto();
void protobuf_AssignDesc_POGOProtos_2fSettings_2fMaster_2fMoveSequenceSettings_2eproto();
void protobuf_ShutdownFile_POGOProtos_2fSettings_2fMaster_2fMoveSequenceSettings_2eproto();

class MoveSequenceSettings;

// ===================================================================

class MoveSequenceSettings : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:POGOProtos.Settings.Master.MoveSequenceSettings) */ {
 public:
  MoveSequenceSettings();
  virtual ~MoveSequenceSettings();

  MoveSequenceSettings(const MoveSequenceSettings& from);

  inline MoveSequenceSettings& operator=(const MoveSequenceSettings& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MoveSequenceSettings& default_instance();

  void Swap(MoveSequenceSettings* other);

  // implements Message ----------------------------------------------

  inline MoveSequenceSettings* New() const { return New(NULL); }

  MoveSequenceSettings* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MoveSequenceSettings& from);
  void MergeFrom(const MoveSequenceSettings& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MoveSequenceSettings* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string sequence = 1;
  int sequence_size() const;
  void clear_sequence();
  static const int kSequenceFieldNumber = 1;
  const ::std::string& sequence(int index) const;
  ::std::string* mutable_sequence(int index);
  void set_sequence(int index, const ::std::string& value);
  void set_sequence(int index, const char* value);
  void set_sequence(int index, const char* value, size_t size);
  ::std::string* add_sequence();
  void add_sequence(const ::std::string& value);
  void add_sequence(const char* value);
  void add_sequence(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& sequence() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_sequence();

  // @@protoc_insertion_point(class_scope:POGOProtos.Settings.Master.MoveSequenceSettings)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::std::string> sequence_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_POGOProtos_2fSettings_2fMaster_2fMoveSequenceSettings_2eproto();
  friend void protobuf_AssignDesc_POGOProtos_2fSettings_2fMaster_2fMoveSequenceSettings_2eproto();
  friend void protobuf_ShutdownFile_POGOProtos_2fSettings_2fMaster_2fMoveSequenceSettings_2eproto();

  void InitAsDefaultInstance();
  static MoveSequenceSettings* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// MoveSequenceSettings

// repeated string sequence = 1;
inline int MoveSequenceSettings::sequence_size() const {
  return sequence_.size();
}
inline void MoveSequenceSettings::clear_sequence() {
  sequence_.Clear();
}
inline const ::std::string& MoveSequenceSettings::sequence(int index) const {
  // @@protoc_insertion_point(field_get:POGOProtos.Settings.Master.MoveSequenceSettings.sequence)
  return sequence_.Get(index);
}
inline ::std::string* MoveSequenceSettings::mutable_sequence(int index) {
  // @@protoc_insertion_point(field_mutable:POGOProtos.Settings.Master.MoveSequenceSettings.sequence)
  return sequence_.Mutable(index);
}
inline void MoveSequenceSettings::set_sequence(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:POGOProtos.Settings.Master.MoveSequenceSettings.sequence)
  sequence_.Mutable(index)->assign(value);
}
inline void MoveSequenceSettings::set_sequence(int index, const char* value) {
  sequence_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:POGOProtos.Settings.Master.MoveSequenceSettings.sequence)
}
inline void MoveSequenceSettings::set_sequence(int index, const char* value, size_t size) {
  sequence_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:POGOProtos.Settings.Master.MoveSequenceSettings.sequence)
}
inline ::std::string* MoveSequenceSettings::add_sequence() {
  // @@protoc_insertion_point(field_add_mutable:POGOProtos.Settings.Master.MoveSequenceSettings.sequence)
  return sequence_.Add();
}
inline void MoveSequenceSettings::add_sequence(const ::std::string& value) {
  sequence_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:POGOProtos.Settings.Master.MoveSequenceSettings.sequence)
}
inline void MoveSequenceSettings::add_sequence(const char* value) {
  sequence_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:POGOProtos.Settings.Master.MoveSequenceSettings.sequence)
}
inline void MoveSequenceSettings::add_sequence(const char* value, size_t size) {
  sequence_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:POGOProtos.Settings.Master.MoveSequenceSettings.sequence)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
MoveSequenceSettings::sequence() const {
  // @@protoc_insertion_point(field_list:POGOProtos.Settings.Master.MoveSequenceSettings.sequence)
  return sequence_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
MoveSequenceSettings::mutable_sequence() {
  // @@protoc_insertion_point(field_mutable_list:POGOProtos.Settings.Master.MoveSequenceSettings.sequence)
  return &sequence_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Master
}  // namespace Settings
}  // namespace POGOProtos

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_POGOProtos_2fSettings_2fMaster_2fMoveSequenceSettings_2eproto__INCLUDED
