// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Data/Player/DailyBonus.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "POGOProtos/Data/Player/DailyBonus.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace POGOProtos {
namespace Data {
namespace Player {

namespace {

const ::google::protobuf::Descriptor* DailyBonus_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DailyBonus_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_POGOProtos_2fData_2fPlayer_2fDailyBonus_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_POGOProtos_2fData_2fPlayer_2fDailyBonus_2eproto() {
  protobuf_AddDesc_POGOProtos_2fData_2fPlayer_2fDailyBonus_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "POGOProtos/Data/Player/DailyBonus.proto");
  GOOGLE_CHECK(file != NULL);
  DailyBonus_descriptor_ = file->message_type(0);
  static const int DailyBonus_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DailyBonus, next_collected_timestamp_ms_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DailyBonus, next_defender_bonus_collect_timestamp_ms_),
  };
  DailyBonus_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      DailyBonus_descriptor_,
      DailyBonus::default_instance_,
      DailyBonus_offsets_,
      -1,
      -1,
      -1,
      sizeof(DailyBonus),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DailyBonus, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DailyBonus, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_POGOProtos_2fData_2fPlayer_2fDailyBonus_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      DailyBonus_descriptor_, &DailyBonus::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_POGOProtos_2fData_2fPlayer_2fDailyBonus_2eproto() {
  delete DailyBonus::default_instance_;
  delete DailyBonus_reflection_;
}

void protobuf_AddDesc_POGOProtos_2fData_2fPlayer_2fDailyBonus_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_POGOProtos_2fData_2fPlayer_2fDailyBonus_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\'POGOProtos/Data/Player/DailyBonus.prot"
    "o\022\026POGOProtos.Data.Player\"c\n\nDailyBonus\022"
    "#\n\033next_collected_timestamp_ms\030\001 \001(\003\0220\n("
    "next_defender_bonus_collect_timestamp_ms"
    "\030\002 \001(\003b\006proto3", 174);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "POGOProtos/Data/Player/DailyBonus.proto", &protobuf_RegisterTypes);
  DailyBonus::default_instance_ = new DailyBonus();
  DailyBonus::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_POGOProtos_2fData_2fPlayer_2fDailyBonus_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_POGOProtos_2fData_2fPlayer_2fDailyBonus_2eproto {
  StaticDescriptorInitializer_POGOProtos_2fData_2fPlayer_2fDailyBonus_2eproto() {
    protobuf_AddDesc_POGOProtos_2fData_2fPlayer_2fDailyBonus_2eproto();
  }
} static_descriptor_initializer_POGOProtos_2fData_2fPlayer_2fDailyBonus_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DailyBonus::kNextCollectedTimestampMsFieldNumber;
const int DailyBonus::kNextDefenderBonusCollectTimestampMsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DailyBonus::DailyBonus()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:POGOProtos.Data.Player.DailyBonus)
}

void DailyBonus::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

DailyBonus::DailyBonus(const DailyBonus& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:POGOProtos.Data.Player.DailyBonus)
}

void DailyBonus::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  next_collected_timestamp_ms_ = GOOGLE_LONGLONG(0);
  next_defender_bonus_collect_timestamp_ms_ = GOOGLE_LONGLONG(0);
}

DailyBonus::~DailyBonus() {
  // @@protoc_insertion_point(destructor:POGOProtos.Data.Player.DailyBonus)
  SharedDtor();
}

void DailyBonus::SharedDtor() {
  if (this != default_instance_) {
  }
}

void DailyBonus::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DailyBonus::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DailyBonus_descriptor_;
}

const DailyBonus& DailyBonus::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_POGOProtos_2fData_2fPlayer_2fDailyBonus_2eproto();
  return *default_instance_;
}

DailyBonus* DailyBonus::default_instance_ = NULL;

DailyBonus* DailyBonus::New(::google::protobuf::Arena* arena) const {
  DailyBonus* n = new DailyBonus;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void DailyBonus::Clear() {
// @@protoc_insertion_point(message_clear_start:POGOProtos.Data.Player.DailyBonus)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(DailyBonus, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<DailyBonus*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(next_collected_timestamp_ms_, next_defender_bonus_collect_timestamp_ms_);

#undef ZR_HELPER_
#undef ZR_

}

bool DailyBonus::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:POGOProtos.Data.Player.DailyBonus)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int64 next_collected_timestamp_ms = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &next_collected_timestamp_ms_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_next_defender_bonus_collect_timestamp_ms;
        break;
      }

      // optional int64 next_defender_bonus_collect_timestamp_ms = 2;
      case 2: {
        if (tag == 16) {
         parse_next_defender_bonus_collect_timestamp_ms:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &next_defender_bonus_collect_timestamp_ms_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:POGOProtos.Data.Player.DailyBonus)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:POGOProtos.Data.Player.DailyBonus)
  return false;
#undef DO_
}

void DailyBonus::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:POGOProtos.Data.Player.DailyBonus)
  // optional int64 next_collected_timestamp_ms = 1;
  if (this->next_collected_timestamp_ms() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->next_collected_timestamp_ms(), output);
  }

  // optional int64 next_defender_bonus_collect_timestamp_ms = 2;
  if (this->next_defender_bonus_collect_timestamp_ms() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->next_defender_bonus_collect_timestamp_ms(), output);
  }

  // @@protoc_insertion_point(serialize_end:POGOProtos.Data.Player.DailyBonus)
}

::google::protobuf::uint8* DailyBonus::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:POGOProtos.Data.Player.DailyBonus)
  // optional int64 next_collected_timestamp_ms = 1;
  if (this->next_collected_timestamp_ms() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->next_collected_timestamp_ms(), target);
  }

  // optional int64 next_defender_bonus_collect_timestamp_ms = 2;
  if (this->next_defender_bonus_collect_timestamp_ms() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->next_defender_bonus_collect_timestamp_ms(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:POGOProtos.Data.Player.DailyBonus)
  return target;
}

int DailyBonus::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:POGOProtos.Data.Player.DailyBonus)
  int total_size = 0;

  // optional int64 next_collected_timestamp_ms = 1;
  if (this->next_collected_timestamp_ms() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->next_collected_timestamp_ms());
  }

  // optional int64 next_defender_bonus_collect_timestamp_ms = 2;
  if (this->next_defender_bonus_collect_timestamp_ms() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->next_defender_bonus_collect_timestamp_ms());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DailyBonus::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:POGOProtos.Data.Player.DailyBonus)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const DailyBonus* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const DailyBonus>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:POGOProtos.Data.Player.DailyBonus)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:POGOProtos.Data.Player.DailyBonus)
    MergeFrom(*source);
  }
}

void DailyBonus::MergeFrom(const DailyBonus& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:POGOProtos.Data.Player.DailyBonus)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.next_collected_timestamp_ms() != 0) {
    set_next_collected_timestamp_ms(from.next_collected_timestamp_ms());
  }
  if (from.next_defender_bonus_collect_timestamp_ms() != 0) {
    set_next_defender_bonus_collect_timestamp_ms(from.next_defender_bonus_collect_timestamp_ms());
  }
}

void DailyBonus::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:POGOProtos.Data.Player.DailyBonus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DailyBonus::CopyFrom(const DailyBonus& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:POGOProtos.Data.Player.DailyBonus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DailyBonus::IsInitialized() const {

  return true;
}

void DailyBonus::Swap(DailyBonus* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DailyBonus::InternalSwap(DailyBonus* other) {
  std::swap(next_collected_timestamp_ms_, other->next_collected_timestamp_ms_);
  std::swap(next_defender_bonus_collect_timestamp_ms_, other->next_defender_bonus_collect_timestamp_ms_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata DailyBonus::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DailyBonus_descriptor_;
  metadata.reflection = DailyBonus_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// DailyBonus

// optional int64 next_collected_timestamp_ms = 1;
void DailyBonus::clear_next_collected_timestamp_ms() {
  next_collected_timestamp_ms_ = GOOGLE_LONGLONG(0);
}
 ::google::protobuf::int64 DailyBonus::next_collected_timestamp_ms() const {
  // @@protoc_insertion_point(field_get:POGOProtos.Data.Player.DailyBonus.next_collected_timestamp_ms)
  return next_collected_timestamp_ms_;
}
 void DailyBonus::set_next_collected_timestamp_ms(::google::protobuf::int64 value) {
  
  next_collected_timestamp_ms_ = value;
  // @@protoc_insertion_point(field_set:POGOProtos.Data.Player.DailyBonus.next_collected_timestamp_ms)
}

// optional int64 next_defender_bonus_collect_timestamp_ms = 2;
void DailyBonus::clear_next_defender_bonus_collect_timestamp_ms() {
  next_defender_bonus_collect_timestamp_ms_ = GOOGLE_LONGLONG(0);
}
 ::google::protobuf::int64 DailyBonus::next_defender_bonus_collect_timestamp_ms() const {
  // @@protoc_insertion_point(field_get:POGOProtos.Data.Player.DailyBonus.next_defender_bonus_collect_timestamp_ms)
  return next_defender_bonus_collect_timestamp_ms_;
}
 void DailyBonus::set_next_defender_bonus_collect_timestamp_ms(::google::protobuf::int64 value) {
  
  next_defender_bonus_collect_timestamp_ms_ = value;
  // @@protoc_insertion_point(field_set:POGOProtos.Data.Player.DailyBonus.next_defender_bonus_collect_timestamp_ms)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Player
}  // namespace Data
}  // namespace POGOProtos

// @@protoc_insertion_point(global_scope)
